/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuthProcedure service. Represents a row in the &quot;OTH_AuthProcedure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.AuthProcedureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.AuthProcedureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuthProcedure
 * @generated
 */
@ProviderType
public interface AuthProcedureModel extends BaseModel<AuthProcedure> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auth procedure model instance should use the {@link AuthProcedure} interface instead.
	 */

	/**
	 * Returns the primary key of this auth procedure.
	 *
	 * @return the primary key of this auth procedure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auth procedure.
	 *
	 * @param primaryKey the primary key of this auth procedure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the auth procedure ID of this auth procedure.
	 *
	 * @return the auth procedure ID of this auth procedure
	 */
	public long getAuthProcedureId();

	/**
	 * Sets the auth procedure ID of this auth procedure.
	 *
	 * @param authProcedureId the auth procedure ID of this auth procedure
	 */
	public void setAuthProcedureId(long authProcedureId);

	/**
	 * Returns the create date of this auth procedure.
	 *
	 * @return the create date of this auth procedure
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this auth procedure.
	 *
	 * @param createDate the create date of this auth procedure
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this auth procedure.
	 *
	 * @return the modified date of this auth procedure
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this auth procedure.
	 *
	 * @param modifiedDate the modified date of this auth procedure
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external authorization ID of this auth procedure.
	 *
	 * @return the external authorization ID of this auth procedure
	 */
	public long getExternalAuthorizationId();

	/**
	 * Sets the external authorization ID of this auth procedure.
	 *
	 * @param externalAuthorizationId the external authorization ID of this auth procedure
	 */
	public void setExternalAuthorizationId(long externalAuthorizationId);

	/**
	 * Returns the auth number of this auth procedure.
	 *
	 * @return the auth number of this auth procedure
	 */
	@AutoEscape
	public String getAuthNumber();

	/**
	 * Sets the auth number of this auth procedure.
	 *
	 * @param authNumber the auth number of this auth procedure
	 */
	public void setAuthNumber(String authNumber);

	/**
	 * Returns the medical code ID of this auth procedure.
	 *
	 * @return the medical code ID of this auth procedure
	 */
	@AutoEscape
	public String getMedicalCodeId();

	/**
	 * Sets the medical code ID of this auth procedure.
	 *
	 * @param medicalCodeId the medical code ID of this auth procedure
	 */
	public void setMedicalCodeId(String medicalCodeId);

	/**
	 * Returns the description of this auth procedure.
	 *
	 * @return the description of this auth procedure
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this auth procedure.
	 *
	 * @param description the description of this auth procedure
	 */
	public void setDescription(String description);

	/**
	 * Returns the external modified date of this auth procedure.
	 *
	 * @return the external modified date of this auth procedure
	 */
	public Date getExternalModifiedDate();

	/**
	 * Sets the external modified date of this auth procedure.
	 *
	 * @param externalModifiedDate the external modified date of this auth procedure
	 */
	public void setExternalModifiedDate(Date externalModifiedDate);

	/**
	 * Returns the external created date of this auth procedure.
	 *
	 * @return the external created date of this auth procedure
	 */
	public Date getExternalCreatedDate();

	/**
	 * Sets the external created date of this auth procedure.
	 *
	 * @param externalCreatedDate the external created date of this auth procedure
	 */
	public void setExternalCreatedDate(Date externalCreatedDate);

}