/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ClaimDetail service. Represents a row in the &quot;OTH_ClaimDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.ClaimDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.ClaimDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClaimDetail
 * @generated
 */
@ProviderType
public interface ClaimDetailModel extends BaseModel<ClaimDetail>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a claim detail model instance should use the {@link ClaimDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this claim detail.
	 *
	 * @return the primary key of this claim detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this claim detail.
	 *
	 * @param primaryKey the primary key of this claim detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the claim detail ID of this claim detail.
	 *
	 * @return the claim detail ID of this claim detail
	 */
	public long getClaimDetailId();

	/**
	 * Sets the claim detail ID of this claim detail.
	 *
	 * @param claimDetailId the claim detail ID of this claim detail
	 */
	public void setClaimDetailId(long claimDetailId);

	/**
	 * Returns the group ID of this claim detail.
	 *
	 * @return the group ID of this claim detail
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this claim detail.
	 *
	 * @param groupId the group ID of this claim detail
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this claim detail.
	 *
	 * @return the company ID of this claim detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this claim detail.
	 *
	 * @param companyId the company ID of this claim detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this claim detail.
	 *
	 * @return the create date of this claim detail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this claim detail.
	 *
	 * @param createDate the create date of this claim detail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this claim detail.
	 *
	 * @return the modified date of this claim detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this claim detail.
	 *
	 * @param modifiedDate the modified date of this claim detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the line ID of this claim detail.
	 *
	 * @return the line ID of this claim detail
	 */
	public long getLineId();

	/**
	 * Sets the line ID of this claim detail.
	 *
	 * @param lineId the line ID of this claim detail
	 */
	public void setLineId(long lineId);

	/**
	 * Returns the external claim ID of this claim detail.
	 *
	 * @return the external claim ID of this claim detail
	 */
	public long getExternalClaimId();

	/**
	 * Sets the external claim ID of this claim detail.
	 *
	 * @param externalClaimId the external claim ID of this claim detail
	 */
	public void setExternalClaimId(long externalClaimId);

	/**
	 * Returns the service from of this claim detail.
	 *
	 * @return the service from of this claim detail
	 */
	public Date getServiceFrom();

	/**
	 * Sets the service from of this claim detail.
	 *
	 * @param serviceFrom the service from of this claim detail
	 */
	public void setServiceFrom(Date serviceFrom);

	/**
	 * Returns the service thru of this claim detail.
	 *
	 * @return the service thru of this claim detail
	 */
	public Date getServiceThru();

	/**
	 * Sets the service thru of this claim detail.
	 *
	 * @param serviceThru the service thru of this claim detail
	 */
	public void setServiceThru(Date serviceThru);

	/**
	 * Returns the result codes of this claim detail.
	 *
	 * @return the result codes of this claim detail
	 */
	@AutoEscape
	public String getResultCodes();

	/**
	 * Sets the result codes of this claim detail.
	 *
	 * @param resultCodes the result codes of this claim detail
	 */
	public void setResultCodes(String resultCodes);

	/**
	 * Returns the procedure code of this claim detail.
	 *
	 * @return the procedure code of this claim detail
	 */
	@AutoEscape
	public String getProcedureCode();

	/**
	 * Sets the procedure code of this claim detail.
	 *
	 * @param procedureCode the procedure code of this claim detail
	 */
	public void setProcedureCode(String procedureCode);

	/**
	 * Returns the charged amount of this claim detail.
	 *
	 * @return the charged amount of this claim detail
	 */
	public double getChargedAmount();

	/**
	 * Sets the charged amount of this claim detail.
	 *
	 * @param chargedAmount the charged amount of this claim detail
	 */
	public void setChargedAmount(double chargedAmount);

	/**
	 * Returns the repriced amount of this claim detail.
	 *
	 * @return the repriced amount of this claim detail
	 */
	public double getRepricedAmount();

	/**
	 * Sets the repriced amount of this claim detail.
	 *
	 * @param repricedAmount the repriced amount of this claim detail
	 */
	public void setRepricedAmount(double repricedAmount);

	/**
	 * Returns the claim amount of this claim detail.
	 *
	 * @return the claim amount of this claim detail
	 */
	public double getClaimAmount();

	/**
	 * Sets the claim amount of this claim detail.
	 *
	 * @param claimAmount the claim amount of this claim detail
	 */
	public void setClaimAmount(double claimAmount);

	/**
	 * Returns the paid date of this claim detail.
	 *
	 * @return the paid date of this claim detail
	 */
	public Date getPaidDate();

	/**
	 * Sets the paid date of this claim detail.
	 *
	 * @param paidDate the paid date of this claim detail
	 */
	public void setPaidDate(Date paidDate);

	/**
	 * Returns the paid amount of this claim detail.
	 *
	 * @return the paid amount of this claim detail
	 */
	public double getPaidAmount();

	/**
	 * Sets the paid amount of this claim detail.
	 *
	 * @param paidAmount the paid amount of this claim detail
	 */
	public void setPaidAmount(double paidAmount);

	/**
	 * Returns the savings amount of this claim detail.
	 *
	 * @return the savings amount of this claim detail
	 */
	public double getSavingsAmount();

	/**
	 * Sets the savings amount of this claim detail.
	 *
	 * @param savingsAmount the savings amount of this claim detail
	 */
	public void setSavingsAmount(double savingsAmount);

	/**
	 * Returns the units of this claim detail.
	 *
	 * @return the units of this claim detail
	 */
	public int getUnits();

	/**
	 * Sets the units of this claim detail.
	 *
	 * @param units the units of this claim detail
	 */
	public void setUnits(int units);

	/**
	 * Returns the coverage of this claim detail.
	 *
	 * @return the coverage of this claim detail
	 */
	@AutoEscape
	public String getCoverage();

	/**
	 * Sets the coverage of this claim detail.
	 *
	 * @param coverage the coverage of this claim detail
	 */
	public void setCoverage(String coverage);

	/**
	 * Returns the line status of this claim detail.
	 *
	 * @return the line status of this claim detail
	 */
	@AutoEscape
	public String getLineStatus();

	/**
	 * Sets the line status of this claim detail.
	 *
	 * @param lineStatus the line status of this claim detail
	 */
	public void setLineStatus(String lineStatus);

	/**
	 * Returns the rev code of this claim detail.
	 *
	 * @return the rev code of this claim detail
	 */
	@AutoEscape
	public String getRevCode();

	/**
	 * Sets the rev code of this claim detail.
	 *
	 * @param revCode the rev code of this claim detail
	 */
	public void setRevCode(String revCode);

	/**
	 * Returns the row processed of this claim detail.
	 *
	 * @return the row processed of this claim detail
	 */
	@AutoEscape
	public String getRowProcessed();

	/**
	 * Sets the row processed of this claim detail.
	 *
	 * @param rowProcessed the row processed of this claim detail
	 */
	public void setRowProcessed(String rowProcessed);

}