/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ReferenceTypeCode service. Represents a row in the &quot;OTH_ReferenceTypeCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.ReferenceTypeCodeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.ReferenceTypeCodeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReferenceTypeCode
 * @generated
 */
@ProviderType
public interface ReferenceTypeCodeModel
	extends BaseModel<ReferenceTypeCode>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reference type code model instance should use the {@link ReferenceTypeCode} interface instead.
	 */

	/**
	 * Returns the primary key of this reference type code.
	 *
	 * @return the primary key of this reference type code
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reference type code.
	 *
	 * @param primaryKey the primary key of this reference type code
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reference type code ID of this reference type code.
	 *
	 * @return the reference type code ID of this reference type code
	 */
	public long getReferenceTypeCodeId();

	/**
	 * Sets the reference type code ID of this reference type code.
	 *
	 * @param referenceTypeCodeId the reference type code ID of this reference type code
	 */
	public void setReferenceTypeCodeId(long referenceTypeCodeId);

	/**
	 * Returns the group ID of this reference type code.
	 *
	 * @return the group ID of this reference type code
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reference type code.
	 *
	 * @param groupId the group ID of this reference type code
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reference type code.
	 *
	 * @return the company ID of this reference type code
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reference type code.
	 *
	 * @param companyId the company ID of this reference type code
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this reference type code.
	 *
	 * @return the create date of this reference type code
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this reference type code.
	 *
	 * @param createDate the create date of this reference type code
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reference type code.
	 *
	 * @return the modified date of this reference type code
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reference type code.
	 *
	 * @param modifiedDate the modified date of this reference type code
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external reference type code ID of this reference type code.
	 *
	 * @return the external reference type code ID of this reference type code
	 */
	public long getExternalReferenceTypeCodeId();

	/**
	 * Sets the external reference type code ID of this reference type code.
	 *
	 * @param externalReferenceTypeCodeId the external reference type code ID of this reference type code
	 */
	public void setExternalReferenceTypeCodeId(
		long externalReferenceTypeCodeId);

	/**
	 * Returns the type of this reference type code.
	 *
	 * @return the type of this reference type code
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this reference type code.
	 *
	 * @param type the type of this reference type code
	 */
	public void setType(String type);

	/**
	 * Returns the key of this reference type code.
	 *
	 * @return the key of this reference type code
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this reference type code.
	 *
	 * @param key the key of this reference type code
	 */
	public void setKey(String key);

	/**
	 * Returns the description of this reference type code.
	 *
	 * @return the description of this reference type code
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this reference type code.
	 *
	 * @param description the description of this reference type code
	 */
	public void setDescription(String description);

	/**
	 * Returns the row processed of this reference type code.
	 *
	 * @return the row processed of this reference type code
	 */
	@AutoEscape
	public String getRowProcessed();

	/**
	 * Sets the row processed of this reference type code.
	 *
	 * @param rowProcessed the row processed of this reference type code
	 */
	public void setRowProcessed(String rowProcessed);

}