/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.model.impl;

import com.argus.oth.account.management.model.AMAnalyticsClaim;
import com.argus.oth.account.management.model.AMAnalyticsClaimModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AMAnalyticsClaim service. Represents a row in the &quot;OTH_AMAnalyticsClaim&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AMAnalyticsClaimModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AMAnalyticsClaimImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMAnalyticsClaimImpl
 * @generated
 */
public class AMAnalyticsClaimModelImpl
	extends BaseModelImpl<AMAnalyticsClaim> implements AMAnalyticsClaimModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a am analytics claim model instance should use the <code>AMAnalyticsClaim</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTH_AMAnalyticsClaim";

	public static final Object[][] TABLE_COLUMNS = {
		{"amAnalyticsClaimId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"clientId", Types.BIGINT},
		{"amAnalyticsClaimDate", Types.TIMESTAMP},
		{"avgClaimTurnAround", Types.INTEGER},
		{"minClaimTurnAround", Types.INTEGER},
		{"maxClaimTurnAround", Types.INTEGER},
		{"claimTurnAroundGoal", Types.INTEGER},
		{"overallAvgClaimTurnAround", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("amAnalyticsClaimId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amAnalyticsClaimDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("avgClaimTurnAround", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("minClaimTurnAround", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("maxClaimTurnAround", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("claimTurnAroundGoal", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("overallAvgClaimTurnAround", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTH_AMAnalyticsClaim (amAnalyticsClaimId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,clientId LONG,amAnalyticsClaimDate DATE null,avgClaimTurnAround INTEGER,minClaimTurnAround INTEGER,maxClaimTurnAround INTEGER,claimTurnAroundGoal INTEGER,overallAvgClaimTurnAround DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table OTH_AMAnalyticsClaim";

	public static final String ORDER_BY_JPQL =
		" ORDER BY amAnalyticsClaim.amAnalyticsClaimDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OTH_AMAnalyticsClaim.amAnalyticsClaimDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public AMAnalyticsClaimModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _amAnalyticsClaimId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAmAnalyticsClaimId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _amAnalyticsClaimId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AMAnalyticsClaim.class;
	}

	@Override
	public String getModelClassName() {
		return AMAnalyticsClaim.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AMAnalyticsClaim, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AMAnalyticsClaim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMAnalyticsClaim, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AMAnalyticsClaim)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AMAnalyticsClaim, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AMAnalyticsClaim, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AMAnalyticsClaim)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AMAnalyticsClaim, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AMAnalyticsClaim, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AMAnalyticsClaim>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AMAnalyticsClaim.class.getClassLoader(), AMAnalyticsClaim.class,
			ModelWrapper.class);

		try {
			Constructor<AMAnalyticsClaim> constructor =
				(Constructor<AMAnalyticsClaim>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AMAnalyticsClaim, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AMAnalyticsClaim, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AMAnalyticsClaim, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<AMAnalyticsClaim, Object>>();
		Map<String, BiConsumer<AMAnalyticsClaim, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AMAnalyticsClaim, ?>>();

		attributeGetterFunctions.put(
			"amAnalyticsClaimId", AMAnalyticsClaim::getAmAnalyticsClaimId);
		attributeSetterBiConsumers.put(
			"amAnalyticsClaimId",
			(BiConsumer<AMAnalyticsClaim, Long>)
				AMAnalyticsClaim::setAmAnalyticsClaimId);
		attributeGetterFunctions.put("groupId", AMAnalyticsClaim::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AMAnalyticsClaim, Long>)AMAnalyticsClaim::setGroupId);
		attributeGetterFunctions.put(
			"companyId", AMAnalyticsClaim::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AMAnalyticsClaim, Long>)AMAnalyticsClaim::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", AMAnalyticsClaim::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AMAnalyticsClaim, Date>)
				AMAnalyticsClaim::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AMAnalyticsClaim::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AMAnalyticsClaim, Date>)
				AMAnalyticsClaim::setModifiedDate);
		attributeGetterFunctions.put("clientId", AMAnalyticsClaim::getClientId);
		attributeSetterBiConsumers.put(
			"clientId",
			(BiConsumer<AMAnalyticsClaim, Long>)AMAnalyticsClaim::setClientId);
		attributeGetterFunctions.put(
			"amAnalyticsClaimDate", AMAnalyticsClaim::getAmAnalyticsClaimDate);
		attributeSetterBiConsumers.put(
			"amAnalyticsClaimDate",
			(BiConsumer<AMAnalyticsClaim, Date>)
				AMAnalyticsClaim::setAmAnalyticsClaimDate);
		attributeGetterFunctions.put(
			"avgClaimTurnAround", AMAnalyticsClaim::getAvgClaimTurnAround);
		attributeSetterBiConsumers.put(
			"avgClaimTurnAround",
			(BiConsumer<AMAnalyticsClaim, Integer>)
				AMAnalyticsClaim::setAvgClaimTurnAround);
		attributeGetterFunctions.put(
			"minClaimTurnAround", AMAnalyticsClaim::getMinClaimTurnAround);
		attributeSetterBiConsumers.put(
			"minClaimTurnAround",
			(BiConsumer<AMAnalyticsClaim, Integer>)
				AMAnalyticsClaim::setMinClaimTurnAround);
		attributeGetterFunctions.put(
			"maxClaimTurnAround", AMAnalyticsClaim::getMaxClaimTurnAround);
		attributeSetterBiConsumers.put(
			"maxClaimTurnAround",
			(BiConsumer<AMAnalyticsClaim, Integer>)
				AMAnalyticsClaim::setMaxClaimTurnAround);
		attributeGetterFunctions.put(
			"claimTurnAroundGoal", AMAnalyticsClaim::getClaimTurnAroundGoal);
		attributeSetterBiConsumers.put(
			"claimTurnAroundGoal",
			(BiConsumer<AMAnalyticsClaim, Integer>)
				AMAnalyticsClaim::setClaimTurnAroundGoal);
		attributeGetterFunctions.put(
			"overallAvgClaimTurnAround",
			AMAnalyticsClaim::getOverallAvgClaimTurnAround);
		attributeSetterBiConsumers.put(
			"overallAvgClaimTurnAround",
			(BiConsumer<AMAnalyticsClaim, Double>)
				AMAnalyticsClaim::setOverallAvgClaimTurnAround);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAmAnalyticsClaimId() {
		return _amAnalyticsClaimId;
	}

	@Override
	public void setAmAnalyticsClaimId(long amAnalyticsClaimId) {
		_amAnalyticsClaimId = amAnalyticsClaimId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_clientId = clientId;
	}

	@Override
	public Date getAmAnalyticsClaimDate() {
		return _amAnalyticsClaimDate;
	}

	@Override
	public void setAmAnalyticsClaimDate(Date amAnalyticsClaimDate) {
		_amAnalyticsClaimDate = amAnalyticsClaimDate;
	}

	@Override
	public int getAvgClaimTurnAround() {
		return _avgClaimTurnAround;
	}

	@Override
	public void setAvgClaimTurnAround(int avgClaimTurnAround) {
		_avgClaimTurnAround = avgClaimTurnAround;
	}

	@Override
	public int getMinClaimTurnAround() {
		return _minClaimTurnAround;
	}

	@Override
	public void setMinClaimTurnAround(int minClaimTurnAround) {
		_minClaimTurnAround = minClaimTurnAround;
	}

	@Override
	public int getMaxClaimTurnAround() {
		return _maxClaimTurnAround;
	}

	@Override
	public void setMaxClaimTurnAround(int maxClaimTurnAround) {
		_maxClaimTurnAround = maxClaimTurnAround;
	}

	@Override
	public int getClaimTurnAroundGoal() {
		return _claimTurnAroundGoal;
	}

	@Override
	public void setClaimTurnAroundGoal(int claimTurnAroundGoal) {
		_claimTurnAroundGoal = claimTurnAroundGoal;
	}

	@Override
	public double getOverallAvgClaimTurnAround() {
		return _overallAvgClaimTurnAround;
	}

	@Override
	public void setOverallAvgClaimTurnAround(double overallAvgClaimTurnAround) {
		_overallAvgClaimTurnAround = overallAvgClaimTurnAround;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AMAnalyticsClaim.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AMAnalyticsClaim toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AMAnalyticsClaim>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AMAnalyticsClaimImpl amAnalyticsClaimImpl = new AMAnalyticsClaimImpl();

		amAnalyticsClaimImpl.setAmAnalyticsClaimId(getAmAnalyticsClaimId());
		amAnalyticsClaimImpl.setGroupId(getGroupId());
		amAnalyticsClaimImpl.setCompanyId(getCompanyId());
		amAnalyticsClaimImpl.setCreateDate(getCreateDate());
		amAnalyticsClaimImpl.setModifiedDate(getModifiedDate());
		amAnalyticsClaimImpl.setClientId(getClientId());
		amAnalyticsClaimImpl.setAmAnalyticsClaimDate(getAmAnalyticsClaimDate());
		amAnalyticsClaimImpl.setAvgClaimTurnAround(getAvgClaimTurnAround());
		amAnalyticsClaimImpl.setMinClaimTurnAround(getMinClaimTurnAround());
		amAnalyticsClaimImpl.setMaxClaimTurnAround(getMaxClaimTurnAround());
		amAnalyticsClaimImpl.setClaimTurnAroundGoal(getClaimTurnAroundGoal());
		amAnalyticsClaimImpl.setOverallAvgClaimTurnAround(
			getOverallAvgClaimTurnAround());

		amAnalyticsClaimImpl.resetOriginalValues();

		return amAnalyticsClaimImpl;
	}

	@Override
	public int compareTo(AMAnalyticsClaim amAnalyticsClaim) {
		int value = 0;

		value = DateUtil.compareTo(
			getAmAnalyticsClaimDate(),
			amAnalyticsClaim.getAmAnalyticsClaimDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AMAnalyticsClaim)) {
			return false;
		}

		AMAnalyticsClaim amAnalyticsClaim = (AMAnalyticsClaim)obj;

		long primaryKey = amAnalyticsClaim.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		AMAnalyticsClaimModelImpl amAnalyticsClaimModelImpl = this;

		amAnalyticsClaimModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<AMAnalyticsClaim> toCacheModel() {
		AMAnalyticsClaimCacheModel amAnalyticsClaimCacheModel =
			new AMAnalyticsClaimCacheModel();

		amAnalyticsClaimCacheModel.amAnalyticsClaimId = getAmAnalyticsClaimId();

		amAnalyticsClaimCacheModel.groupId = getGroupId();

		amAnalyticsClaimCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			amAnalyticsClaimCacheModel.createDate = createDate.getTime();
		}
		else {
			amAnalyticsClaimCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			amAnalyticsClaimCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			amAnalyticsClaimCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		amAnalyticsClaimCacheModel.clientId = getClientId();

		Date amAnalyticsClaimDate = getAmAnalyticsClaimDate();

		if (amAnalyticsClaimDate != null) {
			amAnalyticsClaimCacheModel.amAnalyticsClaimDate =
				amAnalyticsClaimDate.getTime();
		}
		else {
			amAnalyticsClaimCacheModel.amAnalyticsClaimDate = Long.MIN_VALUE;
		}

		amAnalyticsClaimCacheModel.avgClaimTurnAround = getAvgClaimTurnAround();

		amAnalyticsClaimCacheModel.minClaimTurnAround = getMinClaimTurnAround();

		amAnalyticsClaimCacheModel.maxClaimTurnAround = getMaxClaimTurnAround();

		amAnalyticsClaimCacheModel.claimTurnAroundGoal =
			getClaimTurnAroundGoal();

		amAnalyticsClaimCacheModel.overallAvgClaimTurnAround =
			getOverallAvgClaimTurnAround();

		return amAnalyticsClaimCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AMAnalyticsClaim, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AMAnalyticsClaim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMAnalyticsClaim, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((AMAnalyticsClaim)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AMAnalyticsClaim, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AMAnalyticsClaim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMAnalyticsClaim, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AMAnalyticsClaim)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AMAnalyticsClaim>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _amAnalyticsClaimId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _clientId;
	private Date _amAnalyticsClaimDate;
	private int _avgClaimTurnAround;
	private int _minClaimTurnAround;
	private int _maxClaimTurnAround;
	private int _claimTurnAroundGoal;
	private double _overallAvgClaimTurnAround;
	private AMAnalyticsClaim _escapedModel;

}