/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingAMAnalyticsClaim service. Represents a row in the &quot;OTH_StagingAMAnalyticsClaim&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.account.management.model.impl.StagingAMAnalyticsClaimModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.account.management.model.impl.StagingAMAnalyticsClaimImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingAMAnalyticsClaim
 * @generated
 */
@ProviderType
public interface StagingAMAnalyticsClaimModel
	extends BaseModel<StagingAMAnalyticsClaim> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging am analytics claim model instance should use the {@link StagingAMAnalyticsClaim} interface instead.
	 */

	/**
	 * Returns the primary key of this staging am analytics claim.
	 *
	 * @return the primary key of this staging am analytics claim
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging am analytics claim.
	 *
	 * @param primaryKey the primary key of this staging am analytics claim
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staging am analytics claim ID of this staging am analytics claim.
	 *
	 * @return the staging am analytics claim ID of this staging am analytics claim
	 */
	public long getStagingAMAnalyticsClaimId();

	/**
	 * Sets the staging am analytics claim ID of this staging am analytics claim.
	 *
	 * @param stagingAMAnalyticsClaimId the staging am analytics claim ID of this staging am analytics claim
	 */
	public void setStagingAMAnalyticsClaimId(long stagingAMAnalyticsClaimId);

	/**
	 * Returns the create date of this staging am analytics claim.
	 *
	 * @return the create date of this staging am analytics claim
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging am analytics claim.
	 *
	 * @param createDate the create date of this staging am analytics claim
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging am analytics claim.
	 *
	 * @return the modified date of this staging am analytics claim
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging am analytics claim.
	 *
	 * @param modifiedDate the modified date of this staging am analytics claim
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the client ID of this staging am analytics claim.
	 *
	 * @return the client ID of this staging am analytics claim
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this staging am analytics claim.
	 *
	 * @param clientId the client ID of this staging am analytics claim
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the am analytics claim date of this staging am analytics claim.
	 *
	 * @return the am analytics claim date of this staging am analytics claim
	 */
	@AutoEscape
	public String getAmAnalyticsClaimDate();

	/**
	 * Sets the am analytics claim date of this staging am analytics claim.
	 *
	 * @param amAnalyticsClaimDate the am analytics claim date of this staging am analytics claim
	 */
	public void setAmAnalyticsClaimDate(String amAnalyticsClaimDate);

	/**
	 * Returns the avg claim turn around of this staging am analytics claim.
	 *
	 * @return the avg claim turn around of this staging am analytics claim
	 */
	public int getAvgClaimTurnAround();

	/**
	 * Sets the avg claim turn around of this staging am analytics claim.
	 *
	 * @param avgClaimTurnAround the avg claim turn around of this staging am analytics claim
	 */
	public void setAvgClaimTurnAround(int avgClaimTurnAround);

	/**
	 * Returns the min claim turn around of this staging am analytics claim.
	 *
	 * @return the min claim turn around of this staging am analytics claim
	 */
	public int getMinClaimTurnAround();

	/**
	 * Sets the min claim turn around of this staging am analytics claim.
	 *
	 * @param minClaimTurnAround the min claim turn around of this staging am analytics claim
	 */
	public void setMinClaimTurnAround(int minClaimTurnAround);

	/**
	 * Returns the max claim turn around of this staging am analytics claim.
	 *
	 * @return the max claim turn around of this staging am analytics claim
	 */
	public int getMaxClaimTurnAround();

	/**
	 * Sets the max claim turn around of this staging am analytics claim.
	 *
	 * @param maxClaimTurnAround the max claim turn around of this staging am analytics claim
	 */
	public void setMaxClaimTurnAround(int maxClaimTurnAround);

	/**
	 * Returns the claim turn around goal of this staging am analytics claim.
	 *
	 * @return the claim turn around goal of this staging am analytics claim
	 */
	public int getClaimTurnAroundGoal();

	/**
	 * Sets the claim turn around goal of this staging am analytics claim.
	 *
	 * @param claimTurnAroundGoal the claim turn around goal of this staging am analytics claim
	 */
	public void setClaimTurnAroundGoal(int claimTurnAroundGoal);

	/**
	 * Returns the overall avg claim turn around of this staging am analytics claim.
	 *
	 * @return the overall avg claim turn around of this staging am analytics claim
	 */
	public double getOverallAvgClaimTurnAround();

	/**
	 * Sets the overall avg claim turn around of this staging am analytics claim.
	 *
	 * @param overallAvgClaimTurnAround the overall avg claim turn around of this staging am analytics claim
	 */
	public void setOverallAvgClaimTurnAround(double overallAvgClaimTurnAround);

}