/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model.impl;

import com.argus.oth.cases.management.model.StagingClientGroup;
import com.argus.oth.cases.management.model.StagingClientGroupModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StagingClientGroup service. Represents a row in the &quot;OTH_StagingClientGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StagingClientGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StagingClientGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingClientGroupImpl
 * @generated
 */
public class StagingClientGroupModelImpl
	extends BaseModelImpl<StagingClientGroup>
	implements StagingClientGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a staging client group model instance should use the <code>StagingClientGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTH_StagingClientGroup";

	public static final Object[][] TABLE_COLUMNS = {
		{"stagingClientGroupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"externalClientGroupId", Types.BIGINT}, {"clientId", Types.BIGINT},
		{"clientGroup", Types.VARCHAR}, {"clientGroupName", Types.VARCHAR},
		{"externalModifiedDate", Types.VARCHAR},
		{"externalCreatedDate", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("stagingClientGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("externalClientGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientGroup", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clientGroupName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalModifiedDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalCreatedDate", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTH_StagingClientGroup (stagingClientGroupId LONG not null primary key,createDate DATE null,modifiedDate DATE null,externalClientGroupId LONG,clientId LONG,clientGroup VARCHAR(75) null,clientGroupName VARCHAR(1000) null,externalModifiedDate VARCHAR(75) null,externalCreatedDate VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OTH_StagingClientGroup";

	public static final String ORDER_BY_JPQL =
		" ORDER BY stagingClientGroup.stagingClientGroupId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OTH_StagingClientGroup.stagingClientGroupId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long EXTERNALCLIENTGROUPID_COLUMN_BITMASK = 1L;

	public static final long STAGINGCLIENTGROUPID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public StagingClientGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stagingClientGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStagingClientGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stagingClientGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StagingClientGroup.class;
	}

	@Override
	public String getModelClassName() {
		return StagingClientGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StagingClientGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StagingClientGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClientGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StagingClientGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StagingClientGroup, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StagingClientGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StagingClientGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StagingClientGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StagingClientGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, StagingClientGroup>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			StagingClientGroup.class.getClassLoader(), StagingClientGroup.class,
			ModelWrapper.class);

		try {
			Constructor<StagingClientGroup> constructor =
				(Constructor<StagingClientGroup>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<StagingClientGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<StagingClientGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<StagingClientGroup, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<StagingClientGroup, Object>>();
		Map<String, BiConsumer<StagingClientGroup, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<StagingClientGroup, ?>>();

		attributeGetterFunctions.put(
			"stagingClientGroupId",
			StagingClientGroup::getStagingClientGroupId);
		attributeSetterBiConsumers.put(
			"stagingClientGroupId",
			(BiConsumer<StagingClientGroup, Long>)
				StagingClientGroup::setStagingClientGroupId);
		attributeGetterFunctions.put(
			"createDate", StagingClientGroup::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<StagingClientGroup, Date>)
				StagingClientGroup::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", StagingClientGroup::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<StagingClientGroup, Date>)
				StagingClientGroup::setModifiedDate);
		attributeGetterFunctions.put(
			"externalClientGroupId",
			StagingClientGroup::getExternalClientGroupId);
		attributeSetterBiConsumers.put(
			"externalClientGroupId",
			(BiConsumer<StagingClientGroup, Long>)
				StagingClientGroup::setExternalClientGroupId);
		attributeGetterFunctions.put(
			"clientId", StagingClientGroup::getClientId);
		attributeSetterBiConsumers.put(
			"clientId",
			(BiConsumer<StagingClientGroup, Long>)
				StagingClientGroup::setClientId);
		attributeGetterFunctions.put(
			"clientGroup", StagingClientGroup::getClientGroup);
		attributeSetterBiConsumers.put(
			"clientGroup",
			(BiConsumer<StagingClientGroup, String>)
				StagingClientGroup::setClientGroup);
		attributeGetterFunctions.put(
			"clientGroupName", StagingClientGroup::getClientGroupName);
		attributeSetterBiConsumers.put(
			"clientGroupName",
			(BiConsumer<StagingClientGroup, String>)
				StagingClientGroup::setClientGroupName);
		attributeGetterFunctions.put(
			"externalModifiedDate",
			StagingClientGroup::getExternalModifiedDate);
		attributeSetterBiConsumers.put(
			"externalModifiedDate",
			(BiConsumer<StagingClientGroup, String>)
				StagingClientGroup::setExternalModifiedDate);
		attributeGetterFunctions.put(
			"externalCreatedDate", StagingClientGroup::getExternalCreatedDate);
		attributeSetterBiConsumers.put(
			"externalCreatedDate",
			(BiConsumer<StagingClientGroup, String>)
				StagingClientGroup::setExternalCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getStagingClientGroupId() {
		return _stagingClientGroupId;
	}

	@Override
	public void setStagingClientGroupId(long stagingClientGroupId) {
		_columnBitmask = -1L;

		_stagingClientGroupId = stagingClientGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getExternalClientGroupId() {
		return _externalClientGroupId;
	}

	@Override
	public void setExternalClientGroupId(long externalClientGroupId) {
		_columnBitmask |= EXTERNALCLIENTGROUPID_COLUMN_BITMASK;

		if (!_setOriginalExternalClientGroupId) {
			_setOriginalExternalClientGroupId = true;

			_originalExternalClientGroupId = _externalClientGroupId;
		}

		_externalClientGroupId = externalClientGroupId;
	}

	public long getOriginalExternalClientGroupId() {
		return _originalExternalClientGroupId;
	}

	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_clientId = clientId;
	}

	@Override
	public String getClientGroup() {
		if (_clientGroup == null) {
			return "";
		}
		else {
			return _clientGroup;
		}
	}

	@Override
	public void setClientGroup(String clientGroup) {
		_clientGroup = clientGroup;
	}

	@Override
	public String getClientGroupName() {
		if (_clientGroupName == null) {
			return "";
		}
		else {
			return _clientGroupName;
		}
	}

	@Override
	public void setClientGroupName(String clientGroupName) {
		_clientGroupName = clientGroupName;
	}

	@Override
	public String getExternalModifiedDate() {
		if (_externalModifiedDate == null) {
			return "";
		}
		else {
			return _externalModifiedDate;
		}
	}

	@Override
	public void setExternalModifiedDate(String externalModifiedDate) {
		_externalModifiedDate = externalModifiedDate;
	}

	@Override
	public String getExternalCreatedDate() {
		if (_externalCreatedDate == null) {
			return "";
		}
		else {
			return _externalCreatedDate;
		}
	}

	@Override
	public void setExternalCreatedDate(String externalCreatedDate) {
		_externalCreatedDate = externalCreatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, StagingClientGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StagingClientGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StagingClientGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StagingClientGroupImpl stagingClientGroupImpl =
			new StagingClientGroupImpl();

		stagingClientGroupImpl.setStagingClientGroupId(
			getStagingClientGroupId());
		stagingClientGroupImpl.setCreateDate(getCreateDate());
		stagingClientGroupImpl.setModifiedDate(getModifiedDate());
		stagingClientGroupImpl.setExternalClientGroupId(
			getExternalClientGroupId());
		stagingClientGroupImpl.setClientId(getClientId());
		stagingClientGroupImpl.setClientGroup(getClientGroup());
		stagingClientGroupImpl.setClientGroupName(getClientGroupName());
		stagingClientGroupImpl.setExternalModifiedDate(
			getExternalModifiedDate());
		stagingClientGroupImpl.setExternalCreatedDate(getExternalCreatedDate());

		stagingClientGroupImpl.resetOriginalValues();

		return stagingClientGroupImpl;
	}

	@Override
	public int compareTo(StagingClientGroup stagingClientGroup) {
		int value = 0;

		if (getStagingClientGroupId() <
				stagingClientGroup.getStagingClientGroupId()) {

			value = -1;
		}
		else if (getStagingClientGroupId() >
					stagingClientGroup.getStagingClientGroupId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StagingClientGroup)) {
			return false;
		}

		StagingClientGroup stagingClientGroup = (StagingClientGroup)obj;

		long primaryKey = stagingClientGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		StagingClientGroupModelImpl stagingClientGroupModelImpl = this;

		stagingClientGroupModelImpl._setModifiedDate = false;

		stagingClientGroupModelImpl._originalExternalClientGroupId =
			stagingClientGroupModelImpl._externalClientGroupId;

		stagingClientGroupModelImpl._setOriginalExternalClientGroupId = false;

		stagingClientGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StagingClientGroup> toCacheModel() {
		StagingClientGroupCacheModel stagingClientGroupCacheModel =
			new StagingClientGroupCacheModel();

		stagingClientGroupCacheModel.stagingClientGroupId =
			getStagingClientGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			stagingClientGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			stagingClientGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			stagingClientGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			stagingClientGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		stagingClientGroupCacheModel.externalClientGroupId =
			getExternalClientGroupId();

		stagingClientGroupCacheModel.clientId = getClientId();

		stagingClientGroupCacheModel.clientGroup = getClientGroup();

		String clientGroup = stagingClientGroupCacheModel.clientGroup;

		if ((clientGroup != null) && (clientGroup.length() == 0)) {
			stagingClientGroupCacheModel.clientGroup = null;
		}

		stagingClientGroupCacheModel.clientGroupName = getClientGroupName();

		String clientGroupName = stagingClientGroupCacheModel.clientGroupName;

		if ((clientGroupName != null) && (clientGroupName.length() == 0)) {
			stagingClientGroupCacheModel.clientGroupName = null;
		}

		stagingClientGroupCacheModel.externalModifiedDate =
			getExternalModifiedDate();

		String externalModifiedDate =
			stagingClientGroupCacheModel.externalModifiedDate;

		if ((externalModifiedDate != null) &&
			(externalModifiedDate.length() == 0)) {

			stagingClientGroupCacheModel.externalModifiedDate = null;
		}

		stagingClientGroupCacheModel.externalCreatedDate =
			getExternalCreatedDate();

		String externalCreatedDate =
			stagingClientGroupCacheModel.externalCreatedDate;

		if ((externalCreatedDate != null) &&
			(externalCreatedDate.length() == 0)) {

			stagingClientGroupCacheModel.externalCreatedDate = null;
		}

		return stagingClientGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StagingClientGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StagingClientGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClientGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((StagingClientGroup)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<StagingClientGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<StagingClientGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClientGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((StagingClientGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StagingClientGroup>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _stagingClientGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _externalClientGroupId;
	private long _originalExternalClientGroupId;
	private boolean _setOriginalExternalClientGroupId;
	private long _clientId;
	private String _clientGroup;
	private String _clientGroupName;
	private String _externalModifiedDate;
	private String _externalCreatedDate;
	private long _columnBitmask;
	private StagingClientGroup _escapedModel;

}