/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cases service. Represents a row in the &quot;OTH_Cases&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.CasesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.CasesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cases
 * @generated
 */
@ProviderType
public interface CasesModel
	extends BaseModel<Cases>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cases model instance should use the {@link Cases} interface instead.
	 */

	/**
	 * Returns the primary key of this cases.
	 *
	 * @return the primary key of this cases
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cases.
	 *
	 * @param primaryKey the primary key of this cases
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cases.
	 *
	 * @return the uuid of this cases
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cases.
	 *
	 * @param uuid the uuid of this cases
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the case ID of this cases.
	 *
	 * @return the case ID of this cases
	 */
	public long getCaseId();

	/**
	 * Sets the case ID of this cases.
	 *
	 * @param caseId the case ID of this cases
	 */
	public void setCaseId(long caseId);

	/**
	 * Returns the group ID of this cases.
	 *
	 * @return the group ID of this cases
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cases.
	 *
	 * @param groupId the group ID of this cases
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cases.
	 *
	 * @return the company ID of this cases
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cases.
	 *
	 * @param companyId the company ID of this cases
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this cases.
	 *
	 * @return the create date of this cases
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cases.
	 *
	 * @param createDate the create date of this cases
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cases.
	 *
	 * @return the modified date of this cases
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cases.
	 *
	 * @param modifiedDate the modified date of this cases
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external case ID of this cases.
	 *
	 * @return the external case ID of this cases
	 */
	public long getExternalCaseId();

	/**
	 * Sets the external case ID of this cases.
	 *
	 * @param externalCaseId the external case ID of this cases
	 */
	public void setExternalCaseId(long externalCaseId);

	/**
	 * Returns the client ID of this cases.
	 *
	 * @return the client ID of this cases
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this cases.
	 *
	 * @param clientId the client ID of this cases
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the client name of this cases.
	 *
	 * @return the client name of this cases
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this cases.
	 *
	 * @param clientName the client name of this cases
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the client group ID of this cases.
	 *
	 * @return the client group ID of this cases
	 */
	public long getClientGroupId();

	/**
	 * Sets the client group ID of this cases.
	 *
	 * @param clientGroupId the client group ID of this cases
	 */
	public void setClientGroupId(long clientGroupId);

	/**
	 * Returns the case number of this cases.
	 *
	 * @return the case number of this cases
	 */
	@AutoEscape
	public String getCaseNumber();

	/**
	 * Sets the case number of this cases.
	 *
	 * @param caseNumber the case number of this cases
	 */
	public void setCaseNumber(String caseNumber);

	/**
	 * Returns the case start date of this cases.
	 *
	 * @return the case start date of this cases
	 */
	public Date getCaseStartDate();

	/**
	 * Sets the case start date of this cases.
	 *
	 * @param caseStartDate the case start date of this cases
	 */
	public void setCaseStartDate(Date caseStartDate);

	/**
	 * Returns the case end date of this cases.
	 *
	 * @return the case end date of this cases
	 */
	public Date getCaseEndDate();

	/**
	 * Sets the case end date of this cases.
	 *
	 * @param caseEndDate the case end date of this cases
	 */
	public void setCaseEndDate(Date caseEndDate);

	/**
	 * Returns the member ID of this cases.
	 *
	 * @return the member ID of this cases
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this cases.
	 *
	 * @param memberId the member ID of this cases
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the primary diag code of this cases.
	 *
	 * @return the primary diag code of this cases
	 */
	@AutoEscape
	public String getPrimaryDiagCode();

	/**
	 * Sets the primary diag code of this cases.
	 *
	 * @param primaryDiagCode the primary diag code of this cases
	 */
	public void setPrimaryDiagCode(String primaryDiagCode);

	/**
	 * Returns the primary code of this cases.
	 *
	 * @return the primary code of this cases
	 */
	@AutoEscape
	public String getPrimaryCode();

	/**
	 * Sets the primary code of this cases.
	 *
	 * @param primaryCode the primary code of this cases
	 */
	public void setPrimaryCode(String primaryCode);

	/**
	 * Returns the status of this cases.
	 *
	 * @return the status of this cases
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this cases.
	 *
	 * @param status the status of this cases
	 */
	public void setStatus(String status);

	/**
	 * Returns the estimate entry date of this cases.
	 *
	 * @return the estimate entry date of this cases
	 */
	public Date getEstimateEntryDate();

	/**
	 * Sets the estimate entry date of this cases.
	 *
	 * @param estimateEntryDate the estimate entry date of this cases
	 */
	public void setEstimateEntryDate(Date estimateEntryDate);

	/**
	 * Returns the case manager of this cases.
	 *
	 * @return the case manager of this cases
	 */
	@AutoEscape
	public String getCaseManager();

	/**
	 * Sets the case manager of this cases.
	 *
	 * @param caseManager the case manager of this cases
	 */
	public void setCaseManager(String caseManager);

	/**
	 * Returns the consent received date of this cases.
	 *
	 * @return the consent received date of this cases
	 */
	public Date getConsentReceivedDate();

	/**
	 * Sets the consent received date of this cases.
	 *
	 * @param consentReceivedDate the consent received date of this cases
	 */
	public void setConsentReceivedDate(Date consentReceivedDate);

	/**
	 * Returns the medical plan of this cases.
	 *
	 * @return the medical plan of this cases
	 */
	@AutoEscape
	public String getMedicalPlan();

	/**
	 * Sets the medical plan of this cases.
	 *
	 * @param medicalPlan the medical plan of this cases
	 */
	public void setMedicalPlan(String medicalPlan);

	/**
	 * Returns the cost estimate of this cases.
	 *
	 * @return the cost estimate of this cases
	 */
	@AutoEscape
	public String getCostEstimate();

	/**
	 * Sets the cost estimate of this cases.
	 *
	 * @param costEstimate the cost estimate of this cases
	 */
	public void setCostEstimate(String costEstimate);

	/**
	 * Returns the last updated of this cases.
	 *
	 * @return the last updated of this cases
	 */
	public Date getLastUpdated();

	/**
	 * Sets the last updated of this cases.
	 *
	 * @param lastUpdated the last updated of this cases
	 */
	public void setLastUpdated(Date lastUpdated);

	/**
	 * Returns the external created date of this cases.
	 *
	 * @return the external created date of this cases
	 */
	public Date getExternalCreatedDate();

	/**
	 * Sets the external created date of this cases.
	 *
	 * @param externalCreatedDate the external created date of this cases
	 */
	public void setExternalCreatedDate(Date externalCreatedDate);

	/**
	 * Returns the charged amount of this cases.
	 *
	 * @return the charged amount of this cases
	 */
	public double getChargedAmount();

	/**
	 * Sets the charged amount of this cases.
	 *
	 * @param chargedAmount the charged amount of this cases
	 */
	public void setChargedAmount(double chargedAmount);

	/**
	 * Returns the paid amount of this cases.
	 *
	 * @return the paid amount of this cases
	 */
	public double getPaidAmount();

	/**
	 * Sets the paid amount of this cases.
	 *
	 * @param paidAmount the paid amount of this cases
	 */
	public void setPaidAmount(double paidAmount);

	/**
	 * Returns the repriced amount of this cases.
	 *
	 * @return the repriced amount of this cases
	 */
	public double getRepricedAmount();

	/**
	 * Sets the repriced amount of this cases.
	 *
	 * @param repricedAmount the repriced amount of this cases
	 */
	public void setRepricedAmount(double repricedAmount);

	/**
	 * Returns the savings amount of this cases.
	 *
	 * @return the savings amount of this cases
	 */
	public double getSavingsAmount();

	/**
	 * Sets the savings amount of this cases.
	 *
	 * @param savingsAmount the savings amount of this cases
	 */
	public void setSavingsAmount(double savingsAmount);

	/**
	 * Returns the savings percent of this cases.
	 *
	 * @return the savings percent of this cases
	 */
	public double getSavingsPercent();

	/**
	 * Sets the savings percent of this cases.
	 *
	 * @param savingsPercent the savings percent of this cases
	 */
	public void setSavingsPercent(double savingsPercent);

	/**
	 * Returns the treating physician of this cases.
	 *
	 * @return the treating physician of this cases
	 */
	@AutoEscape
	public String getTreatingPhysician();

	/**
	 * Sets the treating physician of this cases.
	 *
	 * @param treatingPhysician the treating physician of this cases
	 */
	public void setTreatingPhysician(String treatingPhysician);

	/**
	 * Returns the primary facility of this cases.
	 *
	 * @return the primary facility of this cases
	 */
	@AutoEscape
	public String getPrimaryFacility();

	/**
	 * Sets the primary facility of this cases.
	 *
	 * @param primaryFacility the primary facility of this cases
	 */
	public void setPrimaryFacility(String primaryFacility);

	/**
	 * Returns the row processed of this cases.
	 *
	 * @return the row processed of this cases
	 */
	@AutoEscape
	public String getRowProcessed();

	/**
	 * Sets the row processed of this cases.
	 *
	 * @param rowProcessed the row processed of this cases
	 */
	public void setRowProcessed(String rowProcessed);

}