/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingClaimDetail service. Represents a row in the &quot;OTH_StagingClaimDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.StagingClaimDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.StagingClaimDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingClaimDetail
 * @generated
 */
@ProviderType
public interface StagingClaimDetailModel extends BaseModel<StagingClaimDetail> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging claim detail model instance should use the {@link StagingClaimDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this staging claim detail.
	 *
	 * @return the primary key of this staging claim detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging claim detail.
	 *
	 * @param primaryKey the primary key of this staging claim detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staging claim detail ID of this staging claim detail.
	 *
	 * @return the staging claim detail ID of this staging claim detail
	 */
	public long getStagingClaimDetailId();

	/**
	 * Sets the staging claim detail ID of this staging claim detail.
	 *
	 * @param stagingClaimDetailId the staging claim detail ID of this staging claim detail
	 */
	public void setStagingClaimDetailId(long stagingClaimDetailId);

	/**
	 * Returns the create date of this staging claim detail.
	 *
	 * @return the create date of this staging claim detail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging claim detail.
	 *
	 * @param createDate the create date of this staging claim detail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging claim detail.
	 *
	 * @return the modified date of this staging claim detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging claim detail.
	 *
	 * @param modifiedDate the modified date of this staging claim detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the line ID of this staging claim detail.
	 *
	 * @return the line ID of this staging claim detail
	 */
	public long getLineId();

	/**
	 * Sets the line ID of this staging claim detail.
	 *
	 * @param lineId the line ID of this staging claim detail
	 */
	public void setLineId(long lineId);

	/**
	 * Returns the external claim ID of this staging claim detail.
	 *
	 * @return the external claim ID of this staging claim detail
	 */
	public long getExternalClaimId();

	/**
	 * Sets the external claim ID of this staging claim detail.
	 *
	 * @param externalClaimId the external claim ID of this staging claim detail
	 */
	public void setExternalClaimId(long externalClaimId);

	/**
	 * Returns the service from of this staging claim detail.
	 *
	 * @return the service from of this staging claim detail
	 */
	@AutoEscape
	public String getServiceFrom();

	/**
	 * Sets the service from of this staging claim detail.
	 *
	 * @param serviceFrom the service from of this staging claim detail
	 */
	public void setServiceFrom(String serviceFrom);

	/**
	 * Returns the service thru of this staging claim detail.
	 *
	 * @return the service thru of this staging claim detail
	 */
	@AutoEscape
	public String getServiceThru();

	/**
	 * Sets the service thru of this staging claim detail.
	 *
	 * @param serviceThru the service thru of this staging claim detail
	 */
	public void setServiceThru(String serviceThru);

	/**
	 * Returns the result codes of this staging claim detail.
	 *
	 * @return the result codes of this staging claim detail
	 */
	@AutoEscape
	public String getResultCodes();

	/**
	 * Sets the result codes of this staging claim detail.
	 *
	 * @param resultCodes the result codes of this staging claim detail
	 */
	public void setResultCodes(String resultCodes);

	/**
	 * Returns the procedure code of this staging claim detail.
	 *
	 * @return the procedure code of this staging claim detail
	 */
	@AutoEscape
	public String getProcedureCode();

	/**
	 * Sets the procedure code of this staging claim detail.
	 *
	 * @param procedureCode the procedure code of this staging claim detail
	 */
	public void setProcedureCode(String procedureCode);

	/**
	 * Returns the charged amount of this staging claim detail.
	 *
	 * @return the charged amount of this staging claim detail
	 */
	public double getChargedAmount();

	/**
	 * Sets the charged amount of this staging claim detail.
	 *
	 * @param chargedAmount the charged amount of this staging claim detail
	 */
	public void setChargedAmount(double chargedAmount);

	/**
	 * Returns the repriced amount of this staging claim detail.
	 *
	 * @return the repriced amount of this staging claim detail
	 */
	public double getRepricedAmount();

	/**
	 * Sets the repriced amount of this staging claim detail.
	 *
	 * @param repricedAmount the repriced amount of this staging claim detail
	 */
	public void setRepricedAmount(double repricedAmount);

	/**
	 * Returns the claim amount of this staging claim detail.
	 *
	 * @return the claim amount of this staging claim detail
	 */
	public double getClaimAmount();

	/**
	 * Sets the claim amount of this staging claim detail.
	 *
	 * @param claimAmount the claim amount of this staging claim detail
	 */
	public void setClaimAmount(double claimAmount);

	/**
	 * Returns the paid date of this staging claim detail.
	 *
	 * @return the paid date of this staging claim detail
	 */
	@AutoEscape
	public String getPaidDate();

	/**
	 * Sets the paid date of this staging claim detail.
	 *
	 * @param paidDate the paid date of this staging claim detail
	 */
	public void setPaidDate(String paidDate);

	/**
	 * Returns the paid amount of this staging claim detail.
	 *
	 * @return the paid amount of this staging claim detail
	 */
	public double getPaidAmount();

	/**
	 * Sets the paid amount of this staging claim detail.
	 *
	 * @param paidAmount the paid amount of this staging claim detail
	 */
	public void setPaidAmount(double paidAmount);

	/**
	 * Returns the savings amount of this staging claim detail.
	 *
	 * @return the savings amount of this staging claim detail
	 */
	public double getSavingsAmount();

	/**
	 * Sets the savings amount of this staging claim detail.
	 *
	 * @param savingsAmount the savings amount of this staging claim detail
	 */
	public void setSavingsAmount(double savingsAmount);

	/**
	 * Returns the units of this staging claim detail.
	 *
	 * @return the units of this staging claim detail
	 */
	public int getUnits();

	/**
	 * Sets the units of this staging claim detail.
	 *
	 * @param units the units of this staging claim detail
	 */
	public void setUnits(int units);

	/**
	 * Returns the coverage of this staging claim detail.
	 *
	 * @return the coverage of this staging claim detail
	 */
	@AutoEscape
	public String getCoverage();

	/**
	 * Sets the coverage of this staging claim detail.
	 *
	 * @param coverage the coverage of this staging claim detail
	 */
	public void setCoverage(String coverage);

	/**
	 * Returns the line status of this staging claim detail.
	 *
	 * @return the line status of this staging claim detail
	 */
	@AutoEscape
	public String getLineStatus();

	/**
	 * Sets the line status of this staging claim detail.
	 *
	 * @param lineStatus the line status of this staging claim detail
	 */
	public void setLineStatus(String lineStatus);

	/**
	 * Returns the rev code of this staging claim detail.
	 *
	 * @return the rev code of this staging claim detail
	 */
	@AutoEscape
	public String getRevCode();

	/**
	 * Sets the rev code of this staging claim detail.
	 *
	 * @param revCode the rev code of this staging claim detail
	 */
	public void setRevCode(String revCode);

	/**
	 * Returns the external modified date of this staging claim detail.
	 *
	 * @return the external modified date of this staging claim detail
	 */
	@AutoEscape
	public String getExternalModifiedDate();

	/**
	 * Sets the external modified date of this staging claim detail.
	 *
	 * @param externalModifiedDate the external modified date of this staging claim detail
	 */
	public void setExternalModifiedDate(String externalModifiedDate);

	/**
	 * Returns the external created date of this staging claim detail.
	 *
	 * @return the external created date of this staging claim detail
	 */
	@AutoEscape
	public String getExternalCreatedDate();

	/**
	 * Sets the external created date of this staging claim detail.
	 *
	 * @param externalCreatedDate the external created date of this staging claim detail
	 */
	public void setExternalCreatedDate(String externalCreatedDate);

}