/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model.impl;

import com.argus.oth.cases.management.model.Claim;
import com.argus.oth.cases.management.model.ClaimModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Claim service. Represents a row in the &quot;OTH_Claim&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ClaimModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClaimImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClaimImpl
 * @generated
 */
public class ClaimModelImpl extends BaseModelImpl<Claim> implements ClaimModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a claim model instance should use the <code>Claim</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTH_Claim";

	public static final Object[][] TABLE_COLUMNS = {
		{"claimId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"externalClaimId", Types.BIGINT},
		{"claimRef", Types.VARCHAR}, {"authorizationNumber", Types.VARCHAR},
		{"serviceFrom", Types.TIMESTAMP}, {"serviceThru", Types.TIMESTAMP},
		{"provider", Types.VARCHAR}, {"prioritizedBill", Types.VARCHAR},
		{"diagCodesCombined", Types.VARCHAR}, {"providerState", Types.VARCHAR},
		{"tpmReceivedDate", Types.TIMESTAMP}, {"claimTurnaround", Types.BIGINT},
		{"billType", Types.VARCHAR}, {"providerNetwork", Types.VARCHAR},
		{"repricedNetwork", Types.VARCHAR}, {"statusSortOrder", Types.BIGINT},
		{"paidDate", Types.TIMESTAMP}, {"paidAmount", Types.DOUBLE},
		{"claimStatus", Types.VARCHAR}, {"rowProcessed", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("claimId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("externalClaimId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("claimRef", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("authorizationNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serviceFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("serviceThru", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("provider", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prioritizedBill", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("diagCodesCombined", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("providerState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tpmReceivedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("claimTurnaround", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("billType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("providerNetwork", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("repricedNetwork", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusSortOrder", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("paidDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("paidAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("claimStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rowProcessed", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTH_Claim (claimId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,externalClaimId LONG,claimRef VARCHAR(75) null,authorizationNumber VARCHAR(75) null,serviceFrom DATE null,serviceThru DATE null,provider VARCHAR(75) null,prioritizedBill VARCHAR(75) null,diagCodesCombined STRING null,providerState VARCHAR(75) null,tpmReceivedDate DATE null,claimTurnaround LONG,billType STRING null,providerNetwork VARCHAR(1000) null,repricedNetwork VARCHAR(1000) null,statusSortOrder LONG,paidDate DATE null,paidAmount DOUBLE,claimStatus VARCHAR(75) null,rowProcessed VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OTH_Claim";

	public static final String ORDER_BY_JPQL =
		" ORDER BY claim.statusSortOrder ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OTH_Claim.statusSortOrder ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long AUTHORIZATIONNUMBER_COLUMN_BITMASK = 1L;

	public static final long CLAIMREF_COLUMN_BITMASK = 2L;

	public static final long ROWPROCESSED_COLUMN_BITMASK = 4L;

	public static final long STATUSSORTORDER_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ClaimModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _claimId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClaimId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _claimId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Claim.class;
	}

	@Override
	public String getModelClassName() {
		return Claim.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Claim, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Claim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Claim, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Claim)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Claim, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Claim, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Claim)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Claim, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Claim, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Claim>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Claim.class.getClassLoader(), Claim.class, ModelWrapper.class);

		try {
			Constructor<Claim> constructor =
				(Constructor<Claim>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Claim, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Claim, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Claim, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Claim, Object>>();
		Map<String, BiConsumer<Claim, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Claim, ?>>();

		attributeGetterFunctions.put("claimId", Claim::getClaimId);
		attributeSetterBiConsumers.put(
			"claimId", (BiConsumer<Claim, Long>)Claim::setClaimId);
		attributeGetterFunctions.put("groupId", Claim::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Claim, Long>)Claim::setGroupId);
		attributeGetterFunctions.put("companyId", Claim::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Claim, Long>)Claim::setCompanyId);
		attributeGetterFunctions.put("createDate", Claim::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Claim, Date>)Claim::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Claim::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Claim, Date>)Claim::setModifiedDate);
		attributeGetterFunctions.put(
			"externalClaimId", Claim::getExternalClaimId);
		attributeSetterBiConsumers.put(
			"externalClaimId",
			(BiConsumer<Claim, Long>)Claim::setExternalClaimId);
		attributeGetterFunctions.put("claimRef", Claim::getClaimRef);
		attributeSetterBiConsumers.put(
			"claimRef", (BiConsumer<Claim, String>)Claim::setClaimRef);
		attributeGetterFunctions.put(
			"authorizationNumber", Claim::getAuthorizationNumber);
		attributeSetterBiConsumers.put(
			"authorizationNumber",
			(BiConsumer<Claim, String>)Claim::setAuthorizationNumber);
		attributeGetterFunctions.put("serviceFrom", Claim::getServiceFrom);
		attributeSetterBiConsumers.put(
			"serviceFrom", (BiConsumer<Claim, Date>)Claim::setServiceFrom);
		attributeGetterFunctions.put("serviceThru", Claim::getServiceThru);
		attributeSetterBiConsumers.put(
			"serviceThru", (BiConsumer<Claim, Date>)Claim::setServiceThru);
		attributeGetterFunctions.put("provider", Claim::getProvider);
		attributeSetterBiConsumers.put(
			"provider", (BiConsumer<Claim, String>)Claim::setProvider);
		attributeGetterFunctions.put(
			"prioritizedBill", Claim::getPrioritizedBill);
		attributeSetterBiConsumers.put(
			"prioritizedBill",
			(BiConsumer<Claim, String>)Claim::setPrioritizedBill);
		attributeGetterFunctions.put(
			"diagCodesCombined", Claim::getDiagCodesCombined);
		attributeSetterBiConsumers.put(
			"diagCodesCombined",
			(BiConsumer<Claim, String>)Claim::setDiagCodesCombined);
		attributeGetterFunctions.put("providerState", Claim::getProviderState);
		attributeSetterBiConsumers.put(
			"providerState",
			(BiConsumer<Claim, String>)Claim::setProviderState);
		attributeGetterFunctions.put(
			"tpmReceivedDate", Claim::getTpmReceivedDate);
		attributeSetterBiConsumers.put(
			"tpmReceivedDate",
			(BiConsumer<Claim, Date>)Claim::setTpmReceivedDate);
		attributeGetterFunctions.put(
			"claimTurnaround", Claim::getClaimTurnaround);
		attributeSetterBiConsumers.put(
			"claimTurnaround",
			(BiConsumer<Claim, Long>)Claim::setClaimTurnaround);
		attributeGetterFunctions.put("billType", Claim::getBillType);
		attributeSetterBiConsumers.put(
			"billType", (BiConsumer<Claim, String>)Claim::setBillType);
		attributeGetterFunctions.put(
			"providerNetwork", Claim::getProviderNetwork);
		attributeSetterBiConsumers.put(
			"providerNetwork",
			(BiConsumer<Claim, String>)Claim::setProviderNetwork);
		attributeGetterFunctions.put(
			"repricedNetwork", Claim::getRepricedNetwork);
		attributeSetterBiConsumers.put(
			"repricedNetwork",
			(BiConsumer<Claim, String>)Claim::setRepricedNetwork);
		attributeGetterFunctions.put(
			"statusSortOrder", Claim::getStatusSortOrder);
		attributeSetterBiConsumers.put(
			"statusSortOrder",
			(BiConsumer<Claim, Long>)Claim::setStatusSortOrder);
		attributeGetterFunctions.put("paidDate", Claim::getPaidDate);
		attributeSetterBiConsumers.put(
			"paidDate", (BiConsumer<Claim, Date>)Claim::setPaidDate);
		attributeGetterFunctions.put("paidAmount", Claim::getPaidAmount);
		attributeSetterBiConsumers.put(
			"paidAmount", (BiConsumer<Claim, Double>)Claim::setPaidAmount);
		attributeGetterFunctions.put("claimStatus", Claim::getClaimStatus);
		attributeSetterBiConsumers.put(
			"claimStatus", (BiConsumer<Claim, String>)Claim::setClaimStatus);
		attributeGetterFunctions.put("rowProcessed", Claim::getRowProcessed);
		attributeSetterBiConsumers.put(
			"rowProcessed", (BiConsumer<Claim, String>)Claim::setRowProcessed);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getClaimId() {
		return _claimId;
	}

	@Override
	public void setClaimId(long claimId) {
		_claimId = claimId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getExternalClaimId() {
		return _externalClaimId;
	}

	@Override
	public void setExternalClaimId(long externalClaimId) {
		_externalClaimId = externalClaimId;
	}

	@Override
	public String getClaimRef() {
		if (_claimRef == null) {
			return "";
		}
		else {
			return _claimRef;
		}
	}

	@Override
	public void setClaimRef(String claimRef) {
		_columnBitmask |= CLAIMREF_COLUMN_BITMASK;

		if (_originalClaimRef == null) {
			_originalClaimRef = _claimRef;
		}

		_claimRef = claimRef;
	}

	public String getOriginalClaimRef() {
		return GetterUtil.getString(_originalClaimRef);
	}

	@Override
	public String getAuthorizationNumber() {
		if (_authorizationNumber == null) {
			return "";
		}
		else {
			return _authorizationNumber;
		}
	}

	@Override
	public void setAuthorizationNumber(String authorizationNumber) {
		_columnBitmask |= AUTHORIZATIONNUMBER_COLUMN_BITMASK;

		if (_originalAuthorizationNumber == null) {
			_originalAuthorizationNumber = _authorizationNumber;
		}

		_authorizationNumber = authorizationNumber;
	}

	public String getOriginalAuthorizationNumber() {
		return GetterUtil.getString(_originalAuthorizationNumber);
	}

	@Override
	public Date getServiceFrom() {
		return _serviceFrom;
	}

	@Override
	public void setServiceFrom(Date serviceFrom) {
		_serviceFrom = serviceFrom;
	}

	@Override
	public Date getServiceThru() {
		return _serviceThru;
	}

	@Override
	public void setServiceThru(Date serviceThru) {
		_serviceThru = serviceThru;
	}

	@Override
	public String getProvider() {
		if (_provider == null) {
			return "";
		}
		else {
			return _provider;
		}
	}

	@Override
	public void setProvider(String provider) {
		_provider = provider;
	}

	@Override
	public String getPrioritizedBill() {
		if (_prioritizedBill == null) {
			return "";
		}
		else {
			return _prioritizedBill;
		}
	}

	@Override
	public void setPrioritizedBill(String prioritizedBill) {
		_prioritizedBill = prioritizedBill;
	}

	@Override
	public String getDiagCodesCombined() {
		if (_diagCodesCombined == null) {
			return "";
		}
		else {
			return _diagCodesCombined;
		}
	}

	@Override
	public void setDiagCodesCombined(String diagCodesCombined) {
		_diagCodesCombined = diagCodesCombined;
	}

	@Override
	public String getProviderState() {
		if (_providerState == null) {
			return "";
		}
		else {
			return _providerState;
		}
	}

	@Override
	public void setProviderState(String providerState) {
		_providerState = providerState;
	}

	@Override
	public Date getTpmReceivedDate() {
		return _tpmReceivedDate;
	}

	@Override
	public void setTpmReceivedDate(Date tpmReceivedDate) {
		_tpmReceivedDate = tpmReceivedDate;
	}

	@Override
	public long getClaimTurnaround() {
		return _claimTurnaround;
	}

	@Override
	public void setClaimTurnaround(long claimTurnaround) {
		_claimTurnaround = claimTurnaround;
	}

	@Override
	public String getBillType() {
		if (_billType == null) {
			return "";
		}
		else {
			return _billType;
		}
	}

	@Override
	public void setBillType(String billType) {
		_billType = billType;
	}

	@Override
	public String getProviderNetwork() {
		if (_providerNetwork == null) {
			return "";
		}
		else {
			return _providerNetwork;
		}
	}

	@Override
	public void setProviderNetwork(String providerNetwork) {
		_providerNetwork = providerNetwork;
	}

	@Override
	public String getRepricedNetwork() {
		if (_repricedNetwork == null) {
			return "";
		}
		else {
			return _repricedNetwork;
		}
	}

	@Override
	public void setRepricedNetwork(String repricedNetwork) {
		_repricedNetwork = repricedNetwork;
	}

	@Override
	public long getStatusSortOrder() {
		return _statusSortOrder;
	}

	@Override
	public void setStatusSortOrder(long statusSortOrder) {
		_columnBitmask = -1L;

		_statusSortOrder = statusSortOrder;
	}

	@Override
	public Date getPaidDate() {
		return _paidDate;
	}

	@Override
	public void setPaidDate(Date paidDate) {
		_paidDate = paidDate;
	}

	@Override
	public double getPaidAmount() {
		return _paidAmount;
	}

	@Override
	public void setPaidAmount(double paidAmount) {
		_paidAmount = paidAmount;
	}

	@Override
	public String getClaimStatus() {
		if (_claimStatus == null) {
			return "";
		}
		else {
			return _claimStatus;
		}
	}

	@Override
	public void setClaimStatus(String claimStatus) {
		_claimStatus = claimStatus;
	}

	@Override
	public String getRowProcessed() {
		if (_rowProcessed == null) {
			return "";
		}
		else {
			return _rowProcessed;
		}
	}

	@Override
	public void setRowProcessed(String rowProcessed) {
		_columnBitmask |= ROWPROCESSED_COLUMN_BITMASK;

		if (_originalRowProcessed == null) {
			_originalRowProcessed = _rowProcessed;
		}

		_rowProcessed = rowProcessed;
	}

	public String getOriginalRowProcessed() {
		return GetterUtil.getString(_originalRowProcessed);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Claim.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Claim toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Claim>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClaimImpl claimImpl = new ClaimImpl();

		claimImpl.setClaimId(getClaimId());
		claimImpl.setGroupId(getGroupId());
		claimImpl.setCompanyId(getCompanyId());
		claimImpl.setCreateDate(getCreateDate());
		claimImpl.setModifiedDate(getModifiedDate());
		claimImpl.setExternalClaimId(getExternalClaimId());
		claimImpl.setClaimRef(getClaimRef());
		claimImpl.setAuthorizationNumber(getAuthorizationNumber());
		claimImpl.setServiceFrom(getServiceFrom());
		claimImpl.setServiceThru(getServiceThru());
		claimImpl.setProvider(getProvider());
		claimImpl.setPrioritizedBill(getPrioritizedBill());
		claimImpl.setDiagCodesCombined(getDiagCodesCombined());
		claimImpl.setProviderState(getProviderState());
		claimImpl.setTpmReceivedDate(getTpmReceivedDate());
		claimImpl.setClaimTurnaround(getClaimTurnaround());
		claimImpl.setBillType(getBillType());
		claimImpl.setProviderNetwork(getProviderNetwork());
		claimImpl.setRepricedNetwork(getRepricedNetwork());
		claimImpl.setStatusSortOrder(getStatusSortOrder());
		claimImpl.setPaidDate(getPaidDate());
		claimImpl.setPaidAmount(getPaidAmount());
		claimImpl.setClaimStatus(getClaimStatus());
		claimImpl.setRowProcessed(getRowProcessed());

		claimImpl.resetOriginalValues();

		return claimImpl;
	}

	@Override
	public int compareTo(Claim claim) {
		int value = 0;

		if (getStatusSortOrder() < claim.getStatusSortOrder()) {
			value = -1;
		}
		else if (getStatusSortOrder() > claim.getStatusSortOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Claim)) {
			return false;
		}

		Claim claim = (Claim)obj;

		long primaryKey = claim.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ClaimModelImpl claimModelImpl = this;

		claimModelImpl._setModifiedDate = false;

		claimModelImpl._originalClaimRef = claimModelImpl._claimRef;

		claimModelImpl._originalAuthorizationNumber =
			claimModelImpl._authorizationNumber;

		claimModelImpl._originalRowProcessed = claimModelImpl._rowProcessed;

		claimModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Claim> toCacheModel() {
		ClaimCacheModel claimCacheModel = new ClaimCacheModel();

		claimCacheModel.claimId = getClaimId();

		claimCacheModel.groupId = getGroupId();

		claimCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			claimCacheModel.createDate = createDate.getTime();
		}
		else {
			claimCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			claimCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			claimCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		claimCacheModel.externalClaimId = getExternalClaimId();

		claimCacheModel.claimRef = getClaimRef();

		String claimRef = claimCacheModel.claimRef;

		if ((claimRef != null) && (claimRef.length() == 0)) {
			claimCacheModel.claimRef = null;
		}

		claimCacheModel.authorizationNumber = getAuthorizationNumber();

		String authorizationNumber = claimCacheModel.authorizationNumber;

		if ((authorizationNumber != null) &&
			(authorizationNumber.length() == 0)) {

			claimCacheModel.authorizationNumber = null;
		}

		Date serviceFrom = getServiceFrom();

		if (serviceFrom != null) {
			claimCacheModel.serviceFrom = serviceFrom.getTime();
		}
		else {
			claimCacheModel.serviceFrom = Long.MIN_VALUE;
		}

		Date serviceThru = getServiceThru();

		if (serviceThru != null) {
			claimCacheModel.serviceThru = serviceThru.getTime();
		}
		else {
			claimCacheModel.serviceThru = Long.MIN_VALUE;
		}

		claimCacheModel.provider = getProvider();

		String provider = claimCacheModel.provider;

		if ((provider != null) && (provider.length() == 0)) {
			claimCacheModel.provider = null;
		}

		claimCacheModel.prioritizedBill = getPrioritizedBill();

		String prioritizedBill = claimCacheModel.prioritizedBill;

		if ((prioritizedBill != null) && (prioritizedBill.length() == 0)) {
			claimCacheModel.prioritizedBill = null;
		}

		claimCacheModel.diagCodesCombined = getDiagCodesCombined();

		String diagCodesCombined = claimCacheModel.diagCodesCombined;

		if ((diagCodesCombined != null) && (diagCodesCombined.length() == 0)) {
			claimCacheModel.diagCodesCombined = null;
		}

		claimCacheModel.providerState = getProviderState();

		String providerState = claimCacheModel.providerState;

		if ((providerState != null) && (providerState.length() == 0)) {
			claimCacheModel.providerState = null;
		}

		Date tpmReceivedDate = getTpmReceivedDate();

		if (tpmReceivedDate != null) {
			claimCacheModel.tpmReceivedDate = tpmReceivedDate.getTime();
		}
		else {
			claimCacheModel.tpmReceivedDate = Long.MIN_VALUE;
		}

		claimCacheModel.claimTurnaround = getClaimTurnaround();

		claimCacheModel.billType = getBillType();

		String billType = claimCacheModel.billType;

		if ((billType != null) && (billType.length() == 0)) {
			claimCacheModel.billType = null;
		}

		claimCacheModel.providerNetwork = getProviderNetwork();

		String providerNetwork = claimCacheModel.providerNetwork;

		if ((providerNetwork != null) && (providerNetwork.length() == 0)) {
			claimCacheModel.providerNetwork = null;
		}

		claimCacheModel.repricedNetwork = getRepricedNetwork();

		String repricedNetwork = claimCacheModel.repricedNetwork;

		if ((repricedNetwork != null) && (repricedNetwork.length() == 0)) {
			claimCacheModel.repricedNetwork = null;
		}

		claimCacheModel.statusSortOrder = getStatusSortOrder();

		Date paidDate = getPaidDate();

		if (paidDate != null) {
			claimCacheModel.paidDate = paidDate.getTime();
		}
		else {
			claimCacheModel.paidDate = Long.MIN_VALUE;
		}

		claimCacheModel.paidAmount = getPaidAmount();

		claimCacheModel.claimStatus = getClaimStatus();

		String claimStatus = claimCacheModel.claimStatus;

		if ((claimStatus != null) && (claimStatus.length() == 0)) {
			claimCacheModel.claimStatus = null;
		}

		claimCacheModel.rowProcessed = getRowProcessed();

		String rowProcessed = claimCacheModel.rowProcessed;

		if ((rowProcessed != null) && (rowProcessed.length() == 0)) {
			claimCacheModel.rowProcessed = null;
		}

		return claimCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Claim, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Claim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Claim, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Claim)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Claim, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Claim, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Claim, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Claim)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Claim>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _claimId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _externalClaimId;
	private String _claimRef;
	private String _originalClaimRef;
	private String _authorizationNumber;
	private String _originalAuthorizationNumber;
	private Date _serviceFrom;
	private Date _serviceThru;
	private String _provider;
	private String _prioritizedBill;
	private String _diagCodesCombined;
	private String _providerState;
	private Date _tpmReceivedDate;
	private long _claimTurnaround;
	private String _billType;
	private String _providerNetwork;
	private String _repricedNetwork;
	private long _statusSortOrder;
	private Date _paidDate;
	private double _paidAmount;
	private String _claimStatus;
	private String _rowProcessed;
	private String _originalRowProcessed;
	private long _columnBitmask;
	private Claim _escapedModel;

}