/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Task service. Represents a row in the &quot;OTH_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.TaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.TaskImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Task
 * @generated
 */
@ProviderType
public interface TaskModel extends BaseModel<Task>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task model instance should use the {@link Task} interface instead.
	 */

	/**
	 * Returns the primary key of this task.
	 *
	 * @return the primary key of this task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task.
	 *
	 * @param primaryKey the primary key of this task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task.
	 *
	 * @return the uuid of this task
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task.
	 *
	 * @param uuid the uuid of this task
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task ID of this task.
	 *
	 * @return the task ID of this task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task.
	 *
	 * @param taskId the task ID of this task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this task.
	 *
	 * @return the group ID of this task
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this task.
	 *
	 * @param groupId the group ID of this task
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task.
	 *
	 * @return the company ID of this task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task.
	 *
	 * @param companyId the company ID of this task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this task.
	 *
	 * @return the create date of this task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task.
	 *
	 * @param createDate the create date of this task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created user ID of this task.
	 *
	 * @return the created user ID of this task
	 */
	public long getCreatedUserId();

	/**
	 * Sets the created user ID of this task.
	 *
	 * @param createdUserId the created user ID of this task
	 */
	public void setCreatedUserId(long createdUserId);

	/**
	 * Returns the created user uuid of this task.
	 *
	 * @return the created user uuid of this task
	 */
	public String getCreatedUserUuid();

	/**
	 * Sets the created user uuid of this task.
	 *
	 * @param createdUserUuid the created user uuid of this task
	 */
	public void setCreatedUserUuid(String createdUserUuid);

	/**
	 * Returns the modified date of this task.
	 *
	 * @return the modified date of this task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task.
	 *
	 * @param modifiedDate the modified date of this task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the case ID of this task.
	 *
	 * @return the case ID of this task
	 */
	public long getCaseId();

	/**
	 * Sets the case ID of this task.
	 *
	 * @param caseId the case ID of this task
	 */
	public void setCaseId(long caseId);

	/**
	 * Returns the external task ID of this task.
	 *
	 * @return the external task ID of this task
	 */
	public long getExternalTaskId();

	/**
	 * Sets the external task ID of this task.
	 *
	 * @param externalTaskId the external task ID of this task
	 */
	public void setExternalTaskId(long externalTaskId);

	/**
	 * Returns the priority of this task.
	 *
	 * @return the priority of this task
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this task.
	 *
	 * @param priority the priority of this task
	 */
	public void setPriority(String priority);

	/**
	 * Returns the start date of this task.
	 *
	 * @return the start date of this task
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this task.
	 *
	 * @param startDate the start date of this task
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this task.
	 *
	 * @return the end date of this task
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this task.
	 *
	 * @param endDate the end date of this task
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the due date of this task.
	 *
	 * @return the due date of this task
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this task.
	 *
	 * @param dueDate the due date of this task
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the task status of this task.
	 *
	 * @return the task status of this task
	 */
	@AutoEscape
	public String getTaskStatus();

	/**
	 * Sets the task status of this task.
	 *
	 * @param taskStatus the task status of this task
	 */
	public void setTaskStatus(String taskStatus);

	/**
	 * Returns the description of this task.
	 *
	 * @return the description of this task
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task.
	 *
	 * @param description the description of this task
	 */
	public void setDescription(String description);

	/**
	 * Returns the process status of this task.
	 *
	 * @return the process status of this task
	 */
	@AutoEscape
	public String getProcessStatus();

	/**
	 * Sets the process status of this task.
	 *
	 * @param processStatus the process status of this task
	 */
	public void setProcessStatus(String processStatus);

	/**
	 * Returns the failure description of this task.
	 *
	 * @return the failure description of this task
	 */
	@AutoEscape
	public String getFailureDescription();

	/**
	 * Sets the failure description of this task.
	 *
	 * @param failureDescription the failure description of this task
	 */
	public void setFailureDescription(String failureDescription);

	/**
	 * Returns the row processed of this task.
	 *
	 * @return the row processed of this task
	 */
	@AutoEscape
	public String getRowProcessed();

	/**
	 * Sets the row processed of this task.
	 *
	 * @param rowProcessed the row processed of this task
	 */
	public void setRowProcessed(String rowProcessed);

}