/*
 * argus-case-eapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Type3;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * CaseTasks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-08T09:53:19.606-08:00")



public class CaseTasks {
  @SerializedName("caseId")
  private BigDecimal caseId = null;

  @SerializedName("taskId")
  private BigDecimal taskId = null;

  @SerializedName("taskType")
  private Type3 taskType = null;

  @SerializedName("taskPriority")
  private Type3 taskPriority = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("dueDate")
  private String dueDate = null;

  @SerializedName("completedDate")
  private String completedDate = null;

  @SerializedName("taskStatus")
  private Type3 taskStatus = null;

  @SerializedName("createdDateTime")
  private String createdDateTime = null;

  @SerializedName("modifiedDateTime")
  private String modifiedDateTime = null;

  public CaseTasks caseId(BigDecimal caseId) {
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getCaseId() {
    return caseId;
  }

  public void setCaseId(BigDecimal caseId) {
    this.caseId = caseId;
  }

  public CaseTasks taskId(BigDecimal taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTaskId() {
    return taskId;
  }

  public void setTaskId(BigDecimal taskId) {
    this.taskId = taskId;
  }

  public CaseTasks taskType(Type3 taskType) {
    this.taskType = taskType;
    return this;
  }

   /**
   * Get taskType
   * @return taskType
  **/
  @ApiModelProperty(value = "")
  public Type3 getTaskType() {
    return taskType;
  }

  public void setTaskType(Type3 taskType) {
    this.taskType = taskType;
  }

  public CaseTasks taskPriority(Type3 taskPriority) {
    this.taskPriority = taskPriority;
    return this;
  }

   /**
   * Get taskPriority
   * @return taskPriority
  **/
  @ApiModelProperty(value = "")
  public Type3 getTaskPriority() {
    return taskPriority;
  }

  public void setTaskPriority(Type3 taskPriority) {
    this.taskPriority = taskPriority;
  }

  public CaseTasks startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public CaseTasks dueDate(String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(value = "")
  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }

  public CaseTasks completedDate(String completedDate) {
    this.completedDate = completedDate;
    return this;
  }

   /**
   * Get completedDate
   * @return completedDate
  **/
  @ApiModelProperty(value = "")
  public String getCompletedDate() {
    return completedDate;
  }

  public void setCompletedDate(String completedDate) {
    this.completedDate = completedDate;
  }

  public CaseTasks taskStatus(Type3 taskStatus) {
    this.taskStatus = taskStatus;
    return this;
  }

   /**
   * Get taskStatus
   * @return taskStatus
  **/
  @ApiModelProperty(value = "")
  public Type3 getTaskStatus() {
    return taskStatus;
  }

  public void setTaskStatus(Type3 taskStatus) {
    this.taskStatus = taskStatus;
  }

  public CaseTasks createdDateTime(String createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public String getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(String createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public CaseTasks modifiedDateTime(String modifiedDateTime) {
    this.modifiedDateTime = modifiedDateTime;
    return this;
  }

   /**
   * Get modifiedDateTime
   * @return modifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public String getModifiedDateTime() {
    return modifiedDateTime;
  }

  public void setModifiedDateTime(String modifiedDateTime) {
    this.modifiedDateTime = modifiedDateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseTasks caseTasks = (CaseTasks) o;
    return Objects.equals(this.caseId, caseTasks.caseId) &&
        Objects.equals(this.taskId, caseTasks.taskId) &&
        Objects.equals(this.taskType, caseTasks.taskType) &&
        Objects.equals(this.taskPriority, caseTasks.taskPriority) &&
        Objects.equals(this.startDate, caseTasks.startDate) &&
        Objects.equals(this.dueDate, caseTasks.dueDate) &&
        Objects.equals(this.completedDate, caseTasks.completedDate) &&
        Objects.equals(this.taskStatus, caseTasks.taskStatus) &&
        Objects.equals(this.createdDateTime, caseTasks.createdDateTime) &&
        Objects.equals(this.modifiedDateTime, caseTasks.modifiedDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseId, taskId, taskType, taskPriority, startDate, dueDate, completedDate, taskStatus, createdDateTime, modifiedDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseTasks {\n");
    
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskType: ").append(toIndentedString(taskType)).append("\n");
    sb.append("    taskPriority: ").append(toIndentedString(taskPriority)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    completedDate: ").append(toIndentedString(completedDate)).append("\n");
    sb.append("    taskStatus: ").append(toIndentedString(taskStatus)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    modifiedDateTime: ").append(toIndentedString(modifiedDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

