/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingReferenceTypeCode service. Represents a row in the &quot;OTH_StagingReferenceTypeCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.StagingReferenceTypeCodeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.StagingReferenceTypeCodeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingReferenceTypeCode
 * @generated
 */
@ProviderType
public interface StagingReferenceTypeCodeModel
	extends BaseModel<StagingReferenceTypeCode> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging reference type code model instance should use the {@link StagingReferenceTypeCode} interface instead.
	 */

	/**
	 * Returns the primary key of this staging reference type code.
	 *
	 * @return the primary key of this staging reference type code
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging reference type code.
	 *
	 * @param primaryKey the primary key of this staging reference type code
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staging reference type code ID of this staging reference type code.
	 *
	 * @return the staging reference type code ID of this staging reference type code
	 */
	public long getStagingReferenceTypeCodeId();

	/**
	 * Sets the staging reference type code ID of this staging reference type code.
	 *
	 * @param stagingReferenceTypeCodeId the staging reference type code ID of this staging reference type code
	 */
	public void setStagingReferenceTypeCodeId(long stagingReferenceTypeCodeId);

	/**
	 * Returns the create date of this staging reference type code.
	 *
	 * @return the create date of this staging reference type code
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging reference type code.
	 *
	 * @param createDate the create date of this staging reference type code
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging reference type code.
	 *
	 * @return the modified date of this staging reference type code
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging reference type code.
	 *
	 * @param modifiedDate the modified date of this staging reference type code
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external reference type code ID of this staging reference type code.
	 *
	 * @return the external reference type code ID of this staging reference type code
	 */
	public long getExternalReferenceTypeCodeId();

	/**
	 * Sets the external reference type code ID of this staging reference type code.
	 *
	 * @param externalReferenceTypeCodeId the external reference type code ID of this staging reference type code
	 */
	public void setExternalReferenceTypeCodeId(
		long externalReferenceTypeCodeId);

	/**
	 * Returns the type of this staging reference type code.
	 *
	 * @return the type of this staging reference type code
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this staging reference type code.
	 *
	 * @param type the type of this staging reference type code
	 */
	public void setType(String type);

	/**
	 * Returns the key of this staging reference type code.
	 *
	 * @return the key of this staging reference type code
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this staging reference type code.
	 *
	 * @param key the key of this staging reference type code
	 */
	public void setKey(String key);

	/**
	 * Returns the description of this staging reference type code.
	 *
	 * @return the description of this staging reference type code
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this staging reference type code.
	 *
	 * @param description the description of this staging reference type code
	 */
	public void setDescription(String description);

	/**
	 * Returns the external modified date of this staging reference type code.
	 *
	 * @return the external modified date of this staging reference type code
	 */
	@AutoEscape
	public String getExternalModifiedDate();

	/**
	 * Sets the external modified date of this staging reference type code.
	 *
	 * @param externalModifiedDate the external modified date of this staging reference type code
	 */
	public void setExternalModifiedDate(String externalModifiedDate);

	/**
	 * Returns the external created date of this staging reference type code.
	 *
	 * @return the external created date of this staging reference type code
	 */
	@AutoEscape
	public String getExternalCreatedDate();

	/**
	 * Sets the external created date of this staging reference type code.
	 *
	 * @param externalCreatedDate the external created date of this staging reference type code
	 */
	public void setExternalCreatedDate(String externalCreatedDate);

}