/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingMember service. Represents a row in the &quot;OTH_StagingMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.StagingMemberModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.StagingMemberImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingMember
 * @generated
 */
@ProviderType
public interface StagingMemberModel extends BaseModel<StagingMember> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging member model instance should use the {@link StagingMember} interface instead.
	 */

	/**
	 * Returns the primary key of this staging member.
	 *
	 * @return the primary key of this staging member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging member.
	 *
	 * @param primaryKey the primary key of this staging member
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staging member ID of this staging member.
	 *
	 * @return the staging member ID of this staging member
	 */
	public long getStagingMemberId();

	/**
	 * Sets the staging member ID of this staging member.
	 *
	 * @param stagingMemberId the staging member ID of this staging member
	 */
	public void setStagingMemberId(long stagingMemberId);

	/**
	 * Returns the create date of this staging member.
	 *
	 * @return the create date of this staging member
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging member.
	 *
	 * @param createDate the create date of this staging member
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging member.
	 *
	 * @return the modified date of this staging member
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging member.
	 *
	 * @param modifiedDate the modified date of this staging member
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external member ID of this staging member.
	 *
	 * @return the external member ID of this staging member
	 */
	public long getExternalMemberId();

	/**
	 * Sets the external member ID of this staging member.
	 *
	 * @param externalMemberId the external member ID of this staging member
	 */
	public void setExternalMemberId(long externalMemberId);

	/**
	 * Returns the client ID of this staging member.
	 *
	 * @return the client ID of this staging member
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this staging member.
	 *
	 * @param clientId the client ID of this staging member
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the client group ID of this staging member.
	 *
	 * @return the client group ID of this staging member
	 */
	public long getClientGroupId();

	/**
	 * Sets the client group ID of this staging member.
	 *
	 * @param clientGroupId the client group ID of this staging member
	 */
	public void setClientGroupId(long clientGroupId);

	/**
	 * Returns the member number of this staging member.
	 *
	 * @return the member number of this staging member
	 */
	@AutoEscape
	public String getMemberNumber();

	/**
	 * Sets the member number of this staging member.
	 *
	 * @param memberNumber the member number of this staging member
	 */
	public void setMemberNumber(String memberNumber);

	/**
	 * Returns the member first name of this staging member.
	 *
	 * @return the member first name of this staging member
	 */
	@AutoEscape
	public String getMemberFirstName();

	/**
	 * Sets the member first name of this staging member.
	 *
	 * @param memberFirstName the member first name of this staging member
	 */
	public void setMemberFirstName(String memberFirstName);

	/**
	 * Returns the member last name of this staging member.
	 *
	 * @return the member last name of this staging member
	 */
	@AutoEscape
	public String getMemberLastName();

	/**
	 * Sets the member last name of this staging member.
	 *
	 * @param memberLastName the member last name of this staging member
	 */
	public void setMemberLastName(String memberLastName);

	/**
	 * Returns the member dob of this staging member.
	 *
	 * @return the member dob of this staging member
	 */
	@AutoEscape
	public String getMemberDOB();

	/**
	 * Sets the member dob of this staging member.
	 *
	 * @param memberDOB the member dob of this staging member
	 */
	public void setMemberDOB(String memberDOB);

	/**
	 * Returns the certification number of this staging member.
	 *
	 * @return the certification number of this staging member
	 */
	@AutoEscape
	public String getCertificationNumber();

	/**
	 * Sets the certification number of this staging member.
	 *
	 * @param certificationNumber the certification number of this staging member
	 */
	public void setCertificationNumber(String certificationNumber);

	/**
	 * Returns the rx number of this staging member.
	 *
	 * @return the rx number of this staging member
	 */
	@AutoEscape
	public String getRxNumber();

	/**
	 * Sets the rx number of this staging member.
	 *
	 * @param rxNumber the rx number of this staging member
	 */
	public void setRxNumber(String rxNumber);

	/**
	 * Returns the external modified date of this staging member.
	 *
	 * @return the external modified date of this staging member
	 */
	@AutoEscape
	public String getExternalModifiedDate();

	/**
	 * Sets the external modified date of this staging member.
	 *
	 * @param externalModifiedDate the external modified date of this staging member
	 */
	public void setExternalModifiedDate(String externalModifiedDate);

	/**
	 * Returns the external created date of this staging member.
	 *
	 * @return the external created date of this staging member
	 */
	@AutoEscape
	public String getExternalCreatedDate();

	/**
	 * Sets the external created date of this staging member.
	 *
	 * @param externalCreatedDate the external created date of this staging member
	 */
	public void setExternalCreatedDate(String externalCreatedDate);

}