/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.claim.model.impl;

import com.argus.oth.claim.model.StagingClaimAnalytics;
import com.argus.oth.claim.model.StagingClaimAnalyticsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StagingClaimAnalytics service. Represents a row in the &quot;OTH_StagingClaimAnalytics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StagingClaimAnalyticsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StagingClaimAnalyticsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingClaimAnalyticsImpl
 * @generated
 */
public class StagingClaimAnalyticsModelImpl
	extends BaseModelImpl<StagingClaimAnalytics>
	implements StagingClaimAnalyticsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a staging claim analytics model instance should use the <code>StagingClaimAnalytics</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTH_StagingClaimAnalytics";

	public static final Object[][] TABLE_COLUMNS = {
		{"stagingClaimAnalyticsId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"externalClientId", Types.BIGINT}, {"clientName", Types.VARCHAR},
		{"claimNumber", Types.VARCHAR}, {"externalCaseId", Types.BIGINT},
		{"claimStatus", Types.VARCHAR}, {"receivedDate", Types.VARCHAR},
		{"serviceDate", Types.VARCHAR}, {"paidDate", Types.VARCHAR},
		{"externalMemberId", Types.BIGINT}, {"memberName", Types.VARCHAR},
		{"providerName", Types.VARCHAR}, {"billType", Types.VARCHAR},
		{"primaryDiagnosis", Types.VARCHAR}, {"chargedAmount", Types.DOUBLE},
		{"paidAmount", Types.DOUBLE}, {"repricedAmount", Types.DOUBLE},
		{"savingsAmount", Types.DOUBLE}, {"chargedPercent", Types.DOUBLE},
		{"repricedPercent", Types.DOUBLE}, {"savingsPercent", Types.DOUBLE},
		{"chargedRange", Types.VARCHAR}, {"paidRange", Types.VARCHAR},
		{"repricedRange", Types.VARCHAR}, {"savingsRange", Types.VARCHAR},
		{"claimAging", Types.BIGINT}, {"procedureCodes", Types.VARCHAR},
		{"resultCodes", Types.VARCHAR}, {"diagnosisCodes", Types.VARCHAR},
		{"country", Types.VARCHAR}, {"state_", Types.VARCHAR},
		{"financialExposure", Types.DOUBLE}, {"repricedNetwork", Types.VARCHAR},
		{"clientGroupName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("stagingClaimAnalyticsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("externalClientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("claimNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalCaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("claimStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("receivedDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serviceDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paidDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalMemberId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("memberName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("providerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("billType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryDiagnosis", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("chargedAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("paidAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("repricedAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("savingsAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("chargedPercent", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("repricedPercent", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("savingsPercent", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("chargedRange", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paidRange", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("repricedRange", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("savingsRange", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("claimAging", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("procedureCodes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resultCodes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("diagnosisCodes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("country", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("financialExposure", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("repricedNetwork", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clientGroupName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTH_StagingClaimAnalytics (stagingClaimAnalyticsId LONG not null primary key,createDate DATE null,modifiedDate DATE null,externalClientId LONG,clientName VARCHAR(75) null,claimNumber VARCHAR(75) null,externalCaseId LONG,claimStatus VARCHAR(75) null,receivedDate VARCHAR(75) null,serviceDate VARCHAR(75) null,paidDate VARCHAR(75) null,externalMemberId LONG,memberName VARCHAR(75) null,providerName VARCHAR(75) null,billType VARCHAR(75) null,primaryDiagnosis VARCHAR(75) null,chargedAmount DOUBLE,paidAmount DOUBLE,repricedAmount DOUBLE,savingsAmount DOUBLE,chargedPercent DOUBLE,repricedPercent DOUBLE,savingsPercent DOUBLE,chargedRange VARCHAR(75) null,paidRange VARCHAR(75) null,repricedRange VARCHAR(75) null,savingsRange VARCHAR(75) null,claimAging LONG,procedureCodes STRING null,resultCodes STRING null,diagnosisCodes STRING null,country VARCHAR(75) null,state_ VARCHAR(75) null,financialExposure DOUBLE,repricedNetwork VARCHAR(75) null,clientGroupName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OTH_StagingClaimAnalytics";

	public static final String ORDER_BY_JPQL =
		" ORDER BY stagingClaimAnalytics.stagingClaimAnalyticsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OTH_StagingClaimAnalytics.stagingClaimAnalyticsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public StagingClaimAnalyticsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stagingClaimAnalyticsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStagingClaimAnalyticsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stagingClaimAnalyticsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StagingClaimAnalytics.class;
	}

	@Override
	public String getModelClassName() {
		return StagingClaimAnalytics.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StagingClaimAnalytics, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StagingClaimAnalytics, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClaimAnalytics, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StagingClaimAnalytics)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StagingClaimAnalytics, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StagingClaimAnalytics, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StagingClaimAnalytics)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StagingClaimAnalytics, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StagingClaimAnalytics, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, StagingClaimAnalytics>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			StagingClaimAnalytics.class.getClassLoader(),
			StagingClaimAnalytics.class, ModelWrapper.class);

		try {
			Constructor<StagingClaimAnalytics> constructor =
				(Constructor<StagingClaimAnalytics>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<StagingClaimAnalytics, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<StagingClaimAnalytics, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<StagingClaimAnalytics, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<StagingClaimAnalytics, Object>>();
		Map<String, BiConsumer<StagingClaimAnalytics, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<StagingClaimAnalytics, ?>>();

		attributeGetterFunctions.put(
			"stagingClaimAnalyticsId",
			StagingClaimAnalytics::getStagingClaimAnalyticsId);
		attributeSetterBiConsumers.put(
			"stagingClaimAnalyticsId",
			(BiConsumer<StagingClaimAnalytics, Long>)
				StagingClaimAnalytics::setStagingClaimAnalyticsId);
		attributeGetterFunctions.put(
			"createDate", StagingClaimAnalytics::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<StagingClaimAnalytics, Date>)
				StagingClaimAnalytics::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", StagingClaimAnalytics::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<StagingClaimAnalytics, Date>)
				StagingClaimAnalytics::setModifiedDate);
		attributeGetterFunctions.put(
			"externalClientId", StagingClaimAnalytics::getExternalClientId);
		attributeSetterBiConsumers.put(
			"externalClientId",
			(BiConsumer<StagingClaimAnalytics, Long>)
				StagingClaimAnalytics::setExternalClientId);
		attributeGetterFunctions.put(
			"clientName", StagingClaimAnalytics::getClientName);
		attributeSetterBiConsumers.put(
			"clientName",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setClientName);
		attributeGetterFunctions.put(
			"claimNumber", StagingClaimAnalytics::getClaimNumber);
		attributeSetterBiConsumers.put(
			"claimNumber",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setClaimNumber);
		attributeGetterFunctions.put(
			"externalCaseId", StagingClaimAnalytics::getExternalCaseId);
		attributeSetterBiConsumers.put(
			"externalCaseId",
			(BiConsumer<StagingClaimAnalytics, Long>)
				StagingClaimAnalytics::setExternalCaseId);
		attributeGetterFunctions.put(
			"claimStatus", StagingClaimAnalytics::getClaimStatus);
		attributeSetterBiConsumers.put(
			"claimStatus",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setClaimStatus);
		attributeGetterFunctions.put(
			"receivedDate", StagingClaimAnalytics::getReceivedDate);
		attributeSetterBiConsumers.put(
			"receivedDate",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setReceivedDate);
		attributeGetterFunctions.put(
			"serviceDate", StagingClaimAnalytics::getServiceDate);
		attributeSetterBiConsumers.put(
			"serviceDate",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setServiceDate);
		attributeGetterFunctions.put(
			"paidDate", StagingClaimAnalytics::getPaidDate);
		attributeSetterBiConsumers.put(
			"paidDate",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setPaidDate);
		attributeGetterFunctions.put(
			"externalMemberId", StagingClaimAnalytics::getExternalMemberId);
		attributeSetterBiConsumers.put(
			"externalMemberId",
			(BiConsumer<StagingClaimAnalytics, Long>)
				StagingClaimAnalytics::setExternalMemberId);
		attributeGetterFunctions.put(
			"memberName", StagingClaimAnalytics::getMemberName);
		attributeSetterBiConsumers.put(
			"memberName",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setMemberName);
		attributeGetterFunctions.put(
			"providerName", StagingClaimAnalytics::getProviderName);
		attributeSetterBiConsumers.put(
			"providerName",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setProviderName);
		attributeGetterFunctions.put(
			"billType", StagingClaimAnalytics::getBillType);
		attributeSetterBiConsumers.put(
			"billType",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setBillType);
		attributeGetterFunctions.put(
			"primaryDiagnosis", StagingClaimAnalytics::getPrimaryDiagnosis);
		attributeSetterBiConsumers.put(
			"primaryDiagnosis",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setPrimaryDiagnosis);
		attributeGetterFunctions.put(
			"chargedAmount", StagingClaimAnalytics::getChargedAmount);
		attributeSetterBiConsumers.put(
			"chargedAmount",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setChargedAmount);
		attributeGetterFunctions.put(
			"paidAmount", StagingClaimAnalytics::getPaidAmount);
		attributeSetterBiConsumers.put(
			"paidAmount",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setPaidAmount);
		attributeGetterFunctions.put(
			"repricedAmount", StagingClaimAnalytics::getRepricedAmount);
		attributeSetterBiConsumers.put(
			"repricedAmount",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setRepricedAmount);
		attributeGetterFunctions.put(
			"savingsAmount", StagingClaimAnalytics::getSavingsAmount);
		attributeSetterBiConsumers.put(
			"savingsAmount",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setSavingsAmount);
		attributeGetterFunctions.put(
			"chargedPercent", StagingClaimAnalytics::getChargedPercent);
		attributeSetterBiConsumers.put(
			"chargedPercent",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setChargedPercent);
		attributeGetterFunctions.put(
			"repricedPercent", StagingClaimAnalytics::getRepricedPercent);
		attributeSetterBiConsumers.put(
			"repricedPercent",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setRepricedPercent);
		attributeGetterFunctions.put(
			"savingsPercent", StagingClaimAnalytics::getSavingsPercent);
		attributeSetterBiConsumers.put(
			"savingsPercent",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setSavingsPercent);
		attributeGetterFunctions.put(
			"chargedRange", StagingClaimAnalytics::getChargedRange);
		attributeSetterBiConsumers.put(
			"chargedRange",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setChargedRange);
		attributeGetterFunctions.put(
			"paidRange", StagingClaimAnalytics::getPaidRange);
		attributeSetterBiConsumers.put(
			"paidRange",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setPaidRange);
		attributeGetterFunctions.put(
			"repricedRange", StagingClaimAnalytics::getRepricedRange);
		attributeSetterBiConsumers.put(
			"repricedRange",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setRepricedRange);
		attributeGetterFunctions.put(
			"savingsRange", StagingClaimAnalytics::getSavingsRange);
		attributeSetterBiConsumers.put(
			"savingsRange",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setSavingsRange);
		attributeGetterFunctions.put(
			"claimAging", StagingClaimAnalytics::getClaimAging);
		attributeSetterBiConsumers.put(
			"claimAging",
			(BiConsumer<StagingClaimAnalytics, Long>)
				StagingClaimAnalytics::setClaimAging);
		attributeGetterFunctions.put(
			"procedureCodes", StagingClaimAnalytics::getProcedureCodes);
		attributeSetterBiConsumers.put(
			"procedureCodes",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setProcedureCodes);
		attributeGetterFunctions.put(
			"resultCodes", StagingClaimAnalytics::getResultCodes);
		attributeSetterBiConsumers.put(
			"resultCodes",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setResultCodes);
		attributeGetterFunctions.put(
			"diagnosisCodes", StagingClaimAnalytics::getDiagnosisCodes);
		attributeSetterBiConsumers.put(
			"diagnosisCodes",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setDiagnosisCodes);
		attributeGetterFunctions.put(
			"country", StagingClaimAnalytics::getCountry);
		attributeSetterBiConsumers.put(
			"country",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setCountry);
		attributeGetterFunctions.put("state", StagingClaimAnalytics::getState);
		attributeSetterBiConsumers.put(
			"state",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setState);
		attributeGetterFunctions.put(
			"financialExposure", StagingClaimAnalytics::getFinancialExposure);
		attributeSetterBiConsumers.put(
			"financialExposure",
			(BiConsumer<StagingClaimAnalytics, Double>)
				StagingClaimAnalytics::setFinancialExposure);
		attributeGetterFunctions.put(
			"repricedNetwork", StagingClaimAnalytics::getRepricedNetwork);
		attributeSetterBiConsumers.put(
			"repricedNetwork",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setRepricedNetwork);
		attributeGetterFunctions.put(
			"clientGroupName", StagingClaimAnalytics::getClientGroupName);
		attributeSetterBiConsumers.put(
			"clientGroupName",
			(BiConsumer<StagingClaimAnalytics, String>)
				StagingClaimAnalytics::setClientGroupName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getStagingClaimAnalyticsId() {
		return _stagingClaimAnalyticsId;
	}

	@Override
	public void setStagingClaimAnalyticsId(long stagingClaimAnalyticsId) {
		_stagingClaimAnalyticsId = stagingClaimAnalyticsId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getExternalClientId() {
		return _externalClientId;
	}

	@Override
	public void setExternalClientId(long externalClientId) {
		_externalClientId = externalClientId;
	}

	@Override
	public String getClientName() {
		if (_clientName == null) {
			return "";
		}
		else {
			return _clientName;
		}
	}

	@Override
	public void setClientName(String clientName) {
		_clientName = clientName;
	}

	@Override
	public String getClaimNumber() {
		if (_claimNumber == null) {
			return "";
		}
		else {
			return _claimNumber;
		}
	}

	@Override
	public void setClaimNumber(String claimNumber) {
		_claimNumber = claimNumber;
	}

	@Override
	public long getExternalCaseId() {
		return _externalCaseId;
	}

	@Override
	public void setExternalCaseId(long externalCaseId) {
		_externalCaseId = externalCaseId;
	}

	@Override
	public String getClaimStatus() {
		if (_claimStatus == null) {
			return "";
		}
		else {
			return _claimStatus;
		}
	}

	@Override
	public void setClaimStatus(String claimStatus) {
		_claimStatus = claimStatus;
	}

	@Override
	public String getReceivedDate() {
		if (_receivedDate == null) {
			return "";
		}
		else {
			return _receivedDate;
		}
	}

	@Override
	public void setReceivedDate(String receivedDate) {
		_receivedDate = receivedDate;
	}

	@Override
	public String getServiceDate() {
		if (_serviceDate == null) {
			return "";
		}
		else {
			return _serviceDate;
		}
	}

	@Override
	public void setServiceDate(String serviceDate) {
		_serviceDate = serviceDate;
	}

	@Override
	public String getPaidDate() {
		if (_paidDate == null) {
			return "";
		}
		else {
			return _paidDate;
		}
	}

	@Override
	public void setPaidDate(String paidDate) {
		_paidDate = paidDate;
	}

	@Override
	public long getExternalMemberId() {
		return _externalMemberId;
	}

	@Override
	public void setExternalMemberId(long externalMemberId) {
		_externalMemberId = externalMemberId;
	}

	@Override
	public String getMemberName() {
		if (_memberName == null) {
			return "";
		}
		else {
			return _memberName;
		}
	}

	@Override
	public void setMemberName(String memberName) {
		_memberName = memberName;
	}

	@Override
	public String getProviderName() {
		if (_providerName == null) {
			return "";
		}
		else {
			return _providerName;
		}
	}

	@Override
	public void setProviderName(String providerName) {
		_providerName = providerName;
	}

	@Override
	public String getBillType() {
		if (_billType == null) {
			return "";
		}
		else {
			return _billType;
		}
	}

	@Override
	public void setBillType(String billType) {
		_billType = billType;
	}

	@Override
	public String getPrimaryDiagnosis() {
		if (_primaryDiagnosis == null) {
			return "";
		}
		else {
			return _primaryDiagnosis;
		}
	}

	@Override
	public void setPrimaryDiagnosis(String primaryDiagnosis) {
		_primaryDiagnosis = primaryDiagnosis;
	}

	@Override
	public double getChargedAmount() {
		return _chargedAmount;
	}

	@Override
	public void setChargedAmount(double chargedAmount) {
		_chargedAmount = chargedAmount;
	}

	@Override
	public double getPaidAmount() {
		return _paidAmount;
	}

	@Override
	public void setPaidAmount(double paidAmount) {
		_paidAmount = paidAmount;
	}

	@Override
	public double getRepricedAmount() {
		return _repricedAmount;
	}

	@Override
	public void setRepricedAmount(double repricedAmount) {
		_repricedAmount = repricedAmount;
	}

	@Override
	public double getSavingsAmount() {
		return _savingsAmount;
	}

	@Override
	public void setSavingsAmount(double savingsAmount) {
		_savingsAmount = savingsAmount;
	}

	@Override
	public double getChargedPercent() {
		return _chargedPercent;
	}

	@Override
	public void setChargedPercent(double chargedPercent) {
		_chargedPercent = chargedPercent;
	}

	@Override
	public double getRepricedPercent() {
		return _repricedPercent;
	}

	@Override
	public void setRepricedPercent(double repricedPercent) {
		_repricedPercent = repricedPercent;
	}

	@Override
	public double getSavingsPercent() {
		return _savingsPercent;
	}

	@Override
	public void setSavingsPercent(double savingsPercent) {
		_savingsPercent = savingsPercent;
	}

	@Override
	public String getChargedRange() {
		if (_chargedRange == null) {
			return "";
		}
		else {
			return _chargedRange;
		}
	}

	@Override
	public void setChargedRange(String chargedRange) {
		_chargedRange = chargedRange;
	}

	@Override
	public String getPaidRange() {
		if (_paidRange == null) {
			return "";
		}
		else {
			return _paidRange;
		}
	}

	@Override
	public void setPaidRange(String paidRange) {
		_paidRange = paidRange;
	}

	@Override
	public String getRepricedRange() {
		if (_repricedRange == null) {
			return "";
		}
		else {
			return _repricedRange;
		}
	}

	@Override
	public void setRepricedRange(String repricedRange) {
		_repricedRange = repricedRange;
	}

	@Override
	public String getSavingsRange() {
		if (_savingsRange == null) {
			return "";
		}
		else {
			return _savingsRange;
		}
	}

	@Override
	public void setSavingsRange(String savingsRange) {
		_savingsRange = savingsRange;
	}

	@Override
	public long getClaimAging() {
		return _claimAging;
	}

	@Override
	public void setClaimAging(long claimAging) {
		_claimAging = claimAging;
	}

	@Override
	public String getProcedureCodes() {
		if (_procedureCodes == null) {
			return "";
		}
		else {
			return _procedureCodes;
		}
	}

	@Override
	public void setProcedureCodes(String procedureCodes) {
		_procedureCodes = procedureCodes;
	}

	@Override
	public String getResultCodes() {
		if (_resultCodes == null) {
			return "";
		}
		else {
			return _resultCodes;
		}
	}

	@Override
	public void setResultCodes(String resultCodes) {
		_resultCodes = resultCodes;
	}

	@Override
	public String getDiagnosisCodes() {
		if (_diagnosisCodes == null) {
			return "";
		}
		else {
			return _diagnosisCodes;
		}
	}

	@Override
	public void setDiagnosisCodes(String diagnosisCodes) {
		_diagnosisCodes = diagnosisCodes;
	}

	@Override
	public String getCountry() {
		if (_country == null) {
			return "";
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		_country = country;
	}

	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		_state = state;
	}

	@Override
	public double getFinancialExposure() {
		return _financialExposure;
	}

	@Override
	public void setFinancialExposure(double financialExposure) {
		_financialExposure = financialExposure;
	}

	@Override
	public String getRepricedNetwork() {
		if (_repricedNetwork == null) {
			return "";
		}
		else {
			return _repricedNetwork;
		}
	}

	@Override
	public void setRepricedNetwork(String repricedNetwork) {
		_repricedNetwork = repricedNetwork;
	}

	@Override
	public String getClientGroupName() {
		if (_clientGroupName == null) {
			return "";
		}
		else {
			return _clientGroupName;
		}
	}

	@Override
	public void setClientGroupName(String clientGroupName) {
		_clientGroupName = clientGroupName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, StagingClaimAnalytics.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StagingClaimAnalytics toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StagingClaimAnalytics>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StagingClaimAnalyticsImpl stagingClaimAnalyticsImpl =
			new StagingClaimAnalyticsImpl();

		stagingClaimAnalyticsImpl.setStagingClaimAnalyticsId(
			getStagingClaimAnalyticsId());
		stagingClaimAnalyticsImpl.setCreateDate(getCreateDate());
		stagingClaimAnalyticsImpl.setModifiedDate(getModifiedDate());
		stagingClaimAnalyticsImpl.setExternalClientId(getExternalClientId());
		stagingClaimAnalyticsImpl.setClientName(getClientName());
		stagingClaimAnalyticsImpl.setClaimNumber(getClaimNumber());
		stagingClaimAnalyticsImpl.setExternalCaseId(getExternalCaseId());
		stagingClaimAnalyticsImpl.setClaimStatus(getClaimStatus());
		stagingClaimAnalyticsImpl.setReceivedDate(getReceivedDate());
		stagingClaimAnalyticsImpl.setServiceDate(getServiceDate());
		stagingClaimAnalyticsImpl.setPaidDate(getPaidDate());
		stagingClaimAnalyticsImpl.setExternalMemberId(getExternalMemberId());
		stagingClaimAnalyticsImpl.setMemberName(getMemberName());
		stagingClaimAnalyticsImpl.setProviderName(getProviderName());
		stagingClaimAnalyticsImpl.setBillType(getBillType());
		stagingClaimAnalyticsImpl.setPrimaryDiagnosis(getPrimaryDiagnosis());
		stagingClaimAnalyticsImpl.setChargedAmount(getChargedAmount());
		stagingClaimAnalyticsImpl.setPaidAmount(getPaidAmount());
		stagingClaimAnalyticsImpl.setRepricedAmount(getRepricedAmount());
		stagingClaimAnalyticsImpl.setSavingsAmount(getSavingsAmount());
		stagingClaimAnalyticsImpl.setChargedPercent(getChargedPercent());
		stagingClaimAnalyticsImpl.setRepricedPercent(getRepricedPercent());
		stagingClaimAnalyticsImpl.setSavingsPercent(getSavingsPercent());
		stagingClaimAnalyticsImpl.setChargedRange(getChargedRange());
		stagingClaimAnalyticsImpl.setPaidRange(getPaidRange());
		stagingClaimAnalyticsImpl.setRepricedRange(getRepricedRange());
		stagingClaimAnalyticsImpl.setSavingsRange(getSavingsRange());
		stagingClaimAnalyticsImpl.setClaimAging(getClaimAging());
		stagingClaimAnalyticsImpl.setProcedureCodes(getProcedureCodes());
		stagingClaimAnalyticsImpl.setResultCodes(getResultCodes());
		stagingClaimAnalyticsImpl.setDiagnosisCodes(getDiagnosisCodes());
		stagingClaimAnalyticsImpl.setCountry(getCountry());
		stagingClaimAnalyticsImpl.setState(getState());
		stagingClaimAnalyticsImpl.setFinancialExposure(getFinancialExposure());
		stagingClaimAnalyticsImpl.setRepricedNetwork(getRepricedNetwork());
		stagingClaimAnalyticsImpl.setClientGroupName(getClientGroupName());

		stagingClaimAnalyticsImpl.resetOriginalValues();

		return stagingClaimAnalyticsImpl;
	}

	@Override
	public int compareTo(StagingClaimAnalytics stagingClaimAnalytics) {
		int value = 0;

		if (getStagingClaimAnalyticsId() <
				stagingClaimAnalytics.getStagingClaimAnalyticsId()) {

			value = -1;
		}
		else if (getStagingClaimAnalyticsId() >
					stagingClaimAnalytics.getStagingClaimAnalyticsId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StagingClaimAnalytics)) {
			return false;
		}

		StagingClaimAnalytics stagingClaimAnalytics =
			(StagingClaimAnalytics)obj;

		long primaryKey = stagingClaimAnalytics.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		StagingClaimAnalyticsModelImpl stagingClaimAnalyticsModelImpl = this;

		stagingClaimAnalyticsModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<StagingClaimAnalytics> toCacheModel() {
		StagingClaimAnalyticsCacheModel stagingClaimAnalyticsCacheModel =
			new StagingClaimAnalyticsCacheModel();

		stagingClaimAnalyticsCacheModel.stagingClaimAnalyticsId =
			getStagingClaimAnalyticsId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			stagingClaimAnalyticsCacheModel.createDate = createDate.getTime();
		}
		else {
			stagingClaimAnalyticsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			stagingClaimAnalyticsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			stagingClaimAnalyticsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		stagingClaimAnalyticsCacheModel.externalClientId =
			getExternalClientId();

		stagingClaimAnalyticsCacheModel.clientName = getClientName();

		String clientName = stagingClaimAnalyticsCacheModel.clientName;

		if ((clientName != null) && (clientName.length() == 0)) {
			stagingClaimAnalyticsCacheModel.clientName = null;
		}

		stagingClaimAnalyticsCacheModel.claimNumber = getClaimNumber();

		String claimNumber = stagingClaimAnalyticsCacheModel.claimNumber;

		if ((claimNumber != null) && (claimNumber.length() == 0)) {
			stagingClaimAnalyticsCacheModel.claimNumber = null;
		}

		stagingClaimAnalyticsCacheModel.externalCaseId = getExternalCaseId();

		stagingClaimAnalyticsCacheModel.claimStatus = getClaimStatus();

		String claimStatus = stagingClaimAnalyticsCacheModel.claimStatus;

		if ((claimStatus != null) && (claimStatus.length() == 0)) {
			stagingClaimAnalyticsCacheModel.claimStatus = null;
		}

		stagingClaimAnalyticsCacheModel.receivedDate = getReceivedDate();

		String receivedDate = stagingClaimAnalyticsCacheModel.receivedDate;

		if ((receivedDate != null) && (receivedDate.length() == 0)) {
			stagingClaimAnalyticsCacheModel.receivedDate = null;
		}

		stagingClaimAnalyticsCacheModel.serviceDate = getServiceDate();

		String serviceDate = stagingClaimAnalyticsCacheModel.serviceDate;

		if ((serviceDate != null) && (serviceDate.length() == 0)) {
			stagingClaimAnalyticsCacheModel.serviceDate = null;
		}

		stagingClaimAnalyticsCacheModel.paidDate = getPaidDate();

		String paidDate = stagingClaimAnalyticsCacheModel.paidDate;

		if ((paidDate != null) && (paidDate.length() == 0)) {
			stagingClaimAnalyticsCacheModel.paidDate = null;
		}

		stagingClaimAnalyticsCacheModel.externalMemberId =
			getExternalMemberId();

		stagingClaimAnalyticsCacheModel.memberName = getMemberName();

		String memberName = stagingClaimAnalyticsCacheModel.memberName;

		if ((memberName != null) && (memberName.length() == 0)) {
			stagingClaimAnalyticsCacheModel.memberName = null;
		}

		stagingClaimAnalyticsCacheModel.providerName = getProviderName();

		String providerName = stagingClaimAnalyticsCacheModel.providerName;

		if ((providerName != null) && (providerName.length() == 0)) {
			stagingClaimAnalyticsCacheModel.providerName = null;
		}

		stagingClaimAnalyticsCacheModel.billType = getBillType();

		String billType = stagingClaimAnalyticsCacheModel.billType;

		if ((billType != null) && (billType.length() == 0)) {
			stagingClaimAnalyticsCacheModel.billType = null;
		}

		stagingClaimAnalyticsCacheModel.primaryDiagnosis =
			getPrimaryDiagnosis();

		String primaryDiagnosis =
			stagingClaimAnalyticsCacheModel.primaryDiagnosis;

		if ((primaryDiagnosis != null) && (primaryDiagnosis.length() == 0)) {
			stagingClaimAnalyticsCacheModel.primaryDiagnosis = null;
		}

		stagingClaimAnalyticsCacheModel.chargedAmount = getChargedAmount();

		stagingClaimAnalyticsCacheModel.paidAmount = getPaidAmount();

		stagingClaimAnalyticsCacheModel.repricedAmount = getRepricedAmount();

		stagingClaimAnalyticsCacheModel.savingsAmount = getSavingsAmount();

		stagingClaimAnalyticsCacheModel.chargedPercent = getChargedPercent();

		stagingClaimAnalyticsCacheModel.repricedPercent = getRepricedPercent();

		stagingClaimAnalyticsCacheModel.savingsPercent = getSavingsPercent();

		stagingClaimAnalyticsCacheModel.chargedRange = getChargedRange();

		String chargedRange = stagingClaimAnalyticsCacheModel.chargedRange;

		if ((chargedRange != null) && (chargedRange.length() == 0)) {
			stagingClaimAnalyticsCacheModel.chargedRange = null;
		}

		stagingClaimAnalyticsCacheModel.paidRange = getPaidRange();

		String paidRange = stagingClaimAnalyticsCacheModel.paidRange;

		if ((paidRange != null) && (paidRange.length() == 0)) {
			stagingClaimAnalyticsCacheModel.paidRange = null;
		}

		stagingClaimAnalyticsCacheModel.repricedRange = getRepricedRange();

		String repricedRange = stagingClaimAnalyticsCacheModel.repricedRange;

		if ((repricedRange != null) && (repricedRange.length() == 0)) {
			stagingClaimAnalyticsCacheModel.repricedRange = null;
		}

		stagingClaimAnalyticsCacheModel.savingsRange = getSavingsRange();

		String savingsRange = stagingClaimAnalyticsCacheModel.savingsRange;

		if ((savingsRange != null) && (savingsRange.length() == 0)) {
			stagingClaimAnalyticsCacheModel.savingsRange = null;
		}

		stagingClaimAnalyticsCacheModel.claimAging = getClaimAging();

		stagingClaimAnalyticsCacheModel.procedureCodes = getProcedureCodes();

		String procedureCodes = stagingClaimAnalyticsCacheModel.procedureCodes;

		if ((procedureCodes != null) && (procedureCodes.length() == 0)) {
			stagingClaimAnalyticsCacheModel.procedureCodes = null;
		}

		stagingClaimAnalyticsCacheModel.resultCodes = getResultCodes();

		String resultCodes = stagingClaimAnalyticsCacheModel.resultCodes;

		if ((resultCodes != null) && (resultCodes.length() == 0)) {
			stagingClaimAnalyticsCacheModel.resultCodes = null;
		}

		stagingClaimAnalyticsCacheModel.diagnosisCodes = getDiagnosisCodes();

		String diagnosisCodes = stagingClaimAnalyticsCacheModel.diagnosisCodes;

		if ((diagnosisCodes != null) && (diagnosisCodes.length() == 0)) {
			stagingClaimAnalyticsCacheModel.diagnosisCodes = null;
		}

		stagingClaimAnalyticsCacheModel.country = getCountry();

		String country = stagingClaimAnalyticsCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			stagingClaimAnalyticsCacheModel.country = null;
		}

		stagingClaimAnalyticsCacheModel.state = getState();

		String state = stagingClaimAnalyticsCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			stagingClaimAnalyticsCacheModel.state = null;
		}

		stagingClaimAnalyticsCacheModel.financialExposure =
			getFinancialExposure();

		stagingClaimAnalyticsCacheModel.repricedNetwork = getRepricedNetwork();

		String repricedNetwork =
			stagingClaimAnalyticsCacheModel.repricedNetwork;

		if ((repricedNetwork != null) && (repricedNetwork.length() == 0)) {
			stagingClaimAnalyticsCacheModel.repricedNetwork = null;
		}

		stagingClaimAnalyticsCacheModel.clientGroupName = getClientGroupName();

		String clientGroupName =
			stagingClaimAnalyticsCacheModel.clientGroupName;

		if ((clientGroupName != null) && (clientGroupName.length() == 0)) {
			stagingClaimAnalyticsCacheModel.clientGroupName = null;
		}

		return stagingClaimAnalyticsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StagingClaimAnalytics, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StagingClaimAnalytics, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClaimAnalytics, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((StagingClaimAnalytics)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<StagingClaimAnalytics, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<StagingClaimAnalytics, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StagingClaimAnalytics, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((StagingClaimAnalytics)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StagingClaimAnalytics>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _stagingClaimAnalyticsId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _externalClientId;
	private String _clientName;
	private String _claimNumber;
	private long _externalCaseId;
	private String _claimStatus;
	private String _receivedDate;
	private String _serviceDate;
	private String _paidDate;
	private long _externalMemberId;
	private String _memberName;
	private String _providerName;
	private String _billType;
	private String _primaryDiagnosis;
	private double _chargedAmount;
	private double _paidAmount;
	private double _repricedAmount;
	private double _savingsAmount;
	private double _chargedPercent;
	private double _repricedPercent;
	private double _savingsPercent;
	private String _chargedRange;
	private String _paidRange;
	private String _repricedRange;
	private String _savingsRange;
	private long _claimAging;
	private String _procedureCodes;
	private String _resultCodes;
	private String _diagnosisCodes;
	private String _country;
	private String _state;
	private double _financialExposure;
	private String _repricedNetwork;
	private String _clientGroupName;
	private StagingClaimAnalytics _escapedModel;

}