/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CasesGroupItem service. Represents a row in the &quot;OTH_CasesGroupItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.CasesGroupItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.CasesGroupItemImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CasesGroupItem
 * @generated
 */
@ProviderType
public interface CasesGroupItemModel
	extends BaseModel<CasesGroupItem>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cases group item model instance should use the {@link CasesGroupItem} interface instead.
	 */

	/**
	 * Returns the primary key of this cases group item.
	 *
	 * @return the primary key of this cases group item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cases group item.
	 *
	 * @param primaryKey the primary key of this cases group item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cases group item ID of this cases group item.
	 *
	 * @return the cases group item ID of this cases group item
	 */
	public long getCasesGroupItemId();

	/**
	 * Sets the cases group item ID of this cases group item.
	 *
	 * @param casesGroupItemId the cases group item ID of this cases group item
	 */
	public void setCasesGroupItemId(long casesGroupItemId);

	/**
	 * Returns the group ID of this cases group item.
	 *
	 * @return the group ID of this cases group item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cases group item.
	 *
	 * @param groupId the group ID of this cases group item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cases group item.
	 *
	 * @return the company ID of this cases group item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cases group item.
	 *
	 * @param companyId the company ID of this cases group item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this cases group item.
	 *
	 * @return the create date of this cases group item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cases group item.
	 *
	 * @param createDate the create date of this cases group item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cases group item.
	 *
	 * @return the modified date of this cases group item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cases group item.
	 *
	 * @param modifiedDate the modified date of this cases group item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this cases group item.
	 *
	 * @return the user ID of this cases group item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cases group item.
	 *
	 * @param userId the user ID of this cases group item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cases group item.
	 *
	 * @return the user uuid of this cases group item
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cases group item.
	 *
	 * @param userUuid the user uuid of this cases group item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the external case ID of this cases group item.
	 *
	 * @return the external case ID of this cases group item
	 */
	public long getExternalCaseId();

	/**
	 * Sets the external case ID of this cases group item.
	 *
	 * @param externalCaseId the external case ID of this cases group item
	 */
	public void setExternalCaseId(long externalCaseId);

	/**
	 * Returns the type of this cases group item.
	 *
	 * @return the type of this cases group item
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this cases group item.
	 *
	 * @param type the type of this cases group item
	 */
	public void setType(String type);

}