/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingTask service. Represents a row in the &quot;OTH_StagingTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.cases.management.model.impl.StagingTaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.cases.management.model.impl.StagingTaskImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingTask
 * @generated
 */
@ProviderType
public interface StagingTaskModel extends BaseModel<StagingTask> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging task model instance should use the {@link StagingTask} interface instead.
	 */

	/**
	 * Returns the primary key of this staging task.
	 *
	 * @return the primary key of this staging task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging task.
	 *
	 * @param primaryKey the primary key of this staging task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this staging task.
	 *
	 * @return the task ID of this staging task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this staging task.
	 *
	 * @param taskId the task ID of this staging task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the create date of this staging task.
	 *
	 * @return the create date of this staging task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging task.
	 *
	 * @param createDate the create date of this staging task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging task.
	 *
	 * @return the modified date of this staging task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging task.
	 *
	 * @param modifiedDate the modified date of this staging task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external case ID of this staging task.
	 *
	 * @return the external case ID of this staging task
	 */
	public long getExternalCaseId();

	/**
	 * Sets the external case ID of this staging task.
	 *
	 * @param externalCaseId the external case ID of this staging task
	 */
	public void setExternalCaseId(long externalCaseId);

	/**
	 * Returns the external task ID of this staging task.
	 *
	 * @return the external task ID of this staging task
	 */
	public long getExternalTaskId();

	/**
	 * Sets the external task ID of this staging task.
	 *
	 * @param externalTaskId the external task ID of this staging task
	 */
	public void setExternalTaskId(long externalTaskId);

	/**
	 * Returns the priority of this staging task.
	 *
	 * @return the priority of this staging task
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this staging task.
	 *
	 * @param priority the priority of this staging task
	 */
	public void setPriority(String priority);

	/**
	 * Returns the start date of this staging task.
	 *
	 * @return the start date of this staging task
	 */
	@AutoEscape
	public String getStartDate();

	/**
	 * Sets the start date of this staging task.
	 *
	 * @param startDate the start date of this staging task
	 */
	public void setStartDate(String startDate);

	/**
	 * Returns the end date of this staging task.
	 *
	 * @return the end date of this staging task
	 */
	@AutoEscape
	public String getEndDate();

	/**
	 * Sets the end date of this staging task.
	 *
	 * @param endDate the end date of this staging task
	 */
	public void setEndDate(String endDate);

	/**
	 * Returns the due date of this staging task.
	 *
	 * @return the due date of this staging task
	 */
	@AutoEscape
	public String getDueDate();

	/**
	 * Sets the due date of this staging task.
	 *
	 * @param dueDate the due date of this staging task
	 */
	public void setDueDate(String dueDate);

	/**
	 * Returns the task status of this staging task.
	 *
	 * @return the task status of this staging task
	 */
	@AutoEscape
	public String getTaskStatus();

	/**
	 * Sets the task status of this staging task.
	 *
	 * @param taskStatus the task status of this staging task
	 */
	public void setTaskStatus(String taskStatus);

	/**
	 * Returns the description of this staging task.
	 *
	 * @return the description of this staging task
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this staging task.
	 *
	 * @param description the description of this staging task
	 */
	public void setDescription(String description);

	/**
	 * Returns the completed flag of this staging task.
	 *
	 * @return the completed flag of this staging task
	 */
	@AutoEscape
	public String getCompletedFlag();

	/**
	 * Sets the completed flag of this staging task.
	 *
	 * @param completedFlag the completed flag of this staging task
	 */
	public void setCompletedFlag(String completedFlag);

	/**
	 * Returns the external create date of this staging task.
	 *
	 * @return the external create date of this staging task
	 */
	@AutoEscape
	public String getExternalCreateDate();

	/**
	 * Sets the external create date of this staging task.
	 *
	 * @param externalCreateDate the external create date of this staging task
	 */
	public void setExternalCreateDate(String externalCreateDate);

	/**
	 * Returns the external modified date of this staging task.
	 *
	 * @return the external modified date of this staging task
	 */
	@AutoEscape
	public String getExternalModifiedDate();

	/**
	 * Sets the external modified date of this staging task.
	 *
	 * @param externalModifiedDate the external modified date of this staging task
	 */
	public void setExternalModifiedDate(String externalModifiedDate);

}