/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.cases.management.model.impl;

import com.argus.oth.cases.management.model.CasesGroupItem;
import com.argus.oth.cases.management.model.CasesGroupItemModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CasesGroupItem service. Represents a row in the &quot;OTH_CasesGroupItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CasesGroupItemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CasesGroupItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CasesGroupItemImpl
 * @generated
 */
public class CasesGroupItemModelImpl
	extends BaseModelImpl<CasesGroupItem> implements CasesGroupItemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cases group item model instance should use the <code>CasesGroupItem</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTH_CasesGroupItem";

	public static final Object[][] TABLE_COLUMNS = {
		{"casesGroupItemId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"userId", Types.BIGINT},
		{"externalCaseId", Types.BIGINT}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("casesGroupItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("externalCaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTH_CasesGroupItem (casesGroupItemId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,externalCaseId LONG,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OTH_CasesGroupItem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY casesGroupItem.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OTH_CasesGroupItem.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long EXTERNALCASEID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CasesGroupItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _casesGroupItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCasesGroupItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _casesGroupItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CasesGroupItem.class;
	}

	@Override
	public String getModelClassName() {
		return CasesGroupItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CasesGroupItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CasesGroupItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CasesGroupItem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CasesGroupItem)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CasesGroupItem, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CasesGroupItem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CasesGroupItem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CasesGroupItem, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CasesGroupItem, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CasesGroupItem>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CasesGroupItem.class.getClassLoader(), CasesGroupItem.class,
			ModelWrapper.class);

		try {
			Constructor<CasesGroupItem> constructor =
				(Constructor<CasesGroupItem>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CasesGroupItem, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CasesGroupItem, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CasesGroupItem, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CasesGroupItem, Object>>();
		Map<String, BiConsumer<CasesGroupItem, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CasesGroupItem, ?>>();

		attributeGetterFunctions.put(
			"casesGroupItemId", CasesGroupItem::getCasesGroupItemId);
		attributeSetterBiConsumers.put(
			"casesGroupItemId",
			(BiConsumer<CasesGroupItem, Long>)
				CasesGroupItem::setCasesGroupItemId);
		attributeGetterFunctions.put("groupId", CasesGroupItem::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CasesGroupItem, Long>)CasesGroupItem::setGroupId);
		attributeGetterFunctions.put("companyId", CasesGroupItem::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CasesGroupItem, Long>)CasesGroupItem::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", CasesGroupItem::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CasesGroupItem, Date>)CasesGroupItem::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CasesGroupItem::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CasesGroupItem, Date>)CasesGroupItem::setModifiedDate);
		attributeGetterFunctions.put("userId", CasesGroupItem::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CasesGroupItem, Long>)CasesGroupItem::setUserId);
		attributeGetterFunctions.put(
			"externalCaseId", CasesGroupItem::getExternalCaseId);
		attributeSetterBiConsumers.put(
			"externalCaseId",
			(BiConsumer<CasesGroupItem, Long>)
				CasesGroupItem::setExternalCaseId);
		attributeGetterFunctions.put("type", CasesGroupItem::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<CasesGroupItem, String>)CasesGroupItem::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCasesGroupItemId() {
		return _casesGroupItemId;
	}

	@Override
	public void setCasesGroupItemId(long casesGroupItemId) {
		_casesGroupItemId = casesGroupItemId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public long getExternalCaseId() {
		return _externalCaseId;
	}

	@Override
	public void setExternalCaseId(long externalCaseId) {
		_columnBitmask |= EXTERNALCASEID_COLUMN_BITMASK;

		if (!_setOriginalExternalCaseId) {
			_setOriginalExternalCaseId = true;

			_originalExternalCaseId = _externalCaseId;
		}

		_externalCaseId = externalCaseId;
	}

	public long getOriginalExternalCaseId() {
		return _originalExternalCaseId;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CasesGroupItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CasesGroupItem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CasesGroupItem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CasesGroupItemImpl casesGroupItemImpl = new CasesGroupItemImpl();

		casesGroupItemImpl.setCasesGroupItemId(getCasesGroupItemId());
		casesGroupItemImpl.setGroupId(getGroupId());
		casesGroupItemImpl.setCompanyId(getCompanyId());
		casesGroupItemImpl.setCreateDate(getCreateDate());
		casesGroupItemImpl.setModifiedDate(getModifiedDate());
		casesGroupItemImpl.setUserId(getUserId());
		casesGroupItemImpl.setExternalCaseId(getExternalCaseId());
		casesGroupItemImpl.setType(getType());

		casesGroupItemImpl.resetOriginalValues();

		return casesGroupItemImpl;
	}

	@Override
	public int compareTo(CasesGroupItem casesGroupItem) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), casesGroupItem.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CasesGroupItem)) {
			return false;
		}

		CasesGroupItem casesGroupItem = (CasesGroupItem)object;

		long primaryKey = casesGroupItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_setModifiedDate = false;
		_originalUserId = _userId;

		_setOriginalUserId = false;

		_originalExternalCaseId = _externalCaseId;

		_setOriginalExternalCaseId = false;

		_originalType = _type;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CasesGroupItem> toCacheModel() {
		CasesGroupItemCacheModel casesGroupItemCacheModel =
			new CasesGroupItemCacheModel();

		casesGroupItemCacheModel.casesGroupItemId = getCasesGroupItemId();

		casesGroupItemCacheModel.groupId = getGroupId();

		casesGroupItemCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			casesGroupItemCacheModel.createDate = createDate.getTime();
		}
		else {
			casesGroupItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			casesGroupItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			casesGroupItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		casesGroupItemCacheModel.userId = getUserId();

		casesGroupItemCacheModel.externalCaseId = getExternalCaseId();

		casesGroupItemCacheModel.type = getType();

		String type = casesGroupItemCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			casesGroupItemCacheModel.type = null;
		}

		return casesGroupItemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CasesGroupItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CasesGroupItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CasesGroupItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CasesGroupItem)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CasesGroupItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CasesGroupItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CasesGroupItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CasesGroupItem)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CasesGroupItem>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _casesGroupItemId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _externalCaseId;
	private long _originalExternalCaseId;
	private boolean _setOriginalExternalCaseId;
	private String _type;
	private String _originalType;
	private long _columnBitmask;
	private CasesGroupItem _escapedModel;

}