/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StagingAMAnalyticsDB service. Represents a row in the &quot;OTH_StagingAMAnalyticsDB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.argus.oth.account.management.model.impl.StagingAMAnalyticsDBModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.argus.oth.account.management.model.impl.StagingAMAnalyticsDBImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StagingAMAnalyticsDB
 * @generated
 */
@ProviderType
public interface StagingAMAnalyticsDBModel
	extends BaseModel<StagingAMAnalyticsDB> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staging am analytics db model instance should use the {@link StagingAMAnalyticsDB} interface instead.
	 */

	/**
	 * Returns the primary key of this staging am analytics db.
	 *
	 * @return the primary key of this staging am analytics db
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staging am analytics db.
	 *
	 * @param primaryKey the primary key of this staging am analytics db
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staging am analytics db ID of this staging am analytics db.
	 *
	 * @return the staging am analytics db ID of this staging am analytics db
	 */
	public long getStagingAMAnalyticsDbId();

	/**
	 * Sets the staging am analytics db ID of this staging am analytics db.
	 *
	 * @param stagingAMAnalyticsDbId the staging am analytics db ID of this staging am analytics db
	 */
	public void setStagingAMAnalyticsDbId(long stagingAMAnalyticsDbId);

	/**
	 * Returns the create date of this staging am analytics db.
	 *
	 * @return the create date of this staging am analytics db
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this staging am analytics db.
	 *
	 * @param createDate the create date of this staging am analytics db
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staging am analytics db.
	 *
	 * @return the modified date of this staging am analytics db
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staging am analytics db.
	 *
	 * @param modifiedDate the modified date of this staging am analytics db
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the client ID of this staging am analytics db.
	 *
	 * @return the client ID of this staging am analytics db
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this staging am analytics db.
	 *
	 * @param clientId the client ID of this staging am analytics db
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the savings percent of this staging am analytics db.
	 *
	 * @return the savings percent of this staging am analytics db
	 */
	public double getSavingsPercent();

	/**
	 * Sets the savings percent of this staging am analytics db.
	 *
	 * @param savingsPercent the savings percent of this staging am analytics db
	 */
	public void setSavingsPercent(double savingsPercent);

	/**
	 * Returns the charged amount of this staging am analytics db.
	 *
	 * @return the charged amount of this staging am analytics db
	 */
	public double getChargedAmount();

	/**
	 * Sets the charged amount of this staging am analytics db.
	 *
	 * @param chargedAmount the charged amount of this staging am analytics db
	 */
	public void setChargedAmount(double chargedAmount);

	/**
	 * Returns the repriced amount of this staging am analytics db.
	 *
	 * @return the repriced amount of this staging am analytics db
	 */
	public double getRepricedAmount();

	/**
	 * Sets the repriced amount of this staging am analytics db.
	 *
	 * @param repricedAmount the repriced amount of this staging am analytics db
	 */
	public void setRepricedAmount(double repricedAmount);

	/**
	 * Returns the avg down time of this staging am analytics db.
	 *
	 * @return the avg down time of this staging am analytics db
	 */
	public double getAvgDownTime();

	/**
	 * Sets the avg down time of this staging am analytics db.
	 *
	 * @param avgDownTime the avg down time of this staging am analytics db
	 */
	public void setAvgDownTime(double avgDownTime);

	/**
	 * Returns the avg speed of answer of this staging am analytics db.
	 *
	 * @return the avg speed of answer of this staging am analytics db
	 */
	public double getAvgSpeedOfAnswer();

	/**
	 * Sets the avg speed of answer of this staging am analytics db.
	 *
	 * @param avgSpeedOfAnswer the avg speed of answer of this staging am analytics db
	 */
	public void setAvgSpeedOfAnswer(double avgSpeedOfAnswer);

	/**
	 * Returns the abandonment rate of this staging am analytics db.
	 *
	 * @return the abandonment rate of this staging am analytics db
	 */
	public double getAbandonmentRate();

	/**
	 * Sets the abandonment rate of this staging am analytics db.
	 *
	 * @param abandonmentRate the abandonment rate of this staging am analytics db
	 */
	public void setAbandonmentRate(double abandonmentRate);

	/**
	 * Returns the claims turnaround of this staging am analytics db.
	 *
	 * @return the claims turnaround of this staging am analytics db
	 */
	public long getClaimsTurnaround();

	/**
	 * Sets the claims turnaround of this staging am analytics db.
	 *
	 * @param claimsTurnaround the claims turnaround of this staging am analytics db
	 */
	public void setClaimsTurnaround(long claimsTurnaround);

	/**
	 * Returns the down time goal of this staging am analytics db.
	 *
	 * @return the down time goal of this staging am analytics db
	 */
	public double getDownTimeGoal();

	/**
	 * Sets the down time goal of this staging am analytics db.
	 *
	 * @param downTimeGoal the down time goal of this staging am analytics db
	 */
	public void setDownTimeGoal(double downTimeGoal);

	/**
	 * Returns the speed of answer goal of this staging am analytics db.
	 *
	 * @return the speed of answer goal of this staging am analytics db
	 */
	public double getSpeedOfAnswerGoal();

	/**
	 * Sets the speed of answer goal of this staging am analytics db.
	 *
	 * @param speedOfAnswerGoal the speed of answer goal of this staging am analytics db
	 */
	public void setSpeedOfAnswerGoal(double speedOfAnswerGoal);

	/**
	 * Returns the abandonment rate goal of this staging am analytics db.
	 *
	 * @return the abandonment rate goal of this staging am analytics db
	 */
	public double getAbandonmentRateGoal();

	/**
	 * Sets the abandonment rate goal of this staging am analytics db.
	 *
	 * @param abandonmentRateGoal the abandonment rate goal of this staging am analytics db
	 */
	public void setAbandonmentRateGoal(double abandonmentRateGoal);

	/**
	 * Returns the claims turnaround goal of this staging am analytics db.
	 *
	 * @return the claims turnaround goal of this staging am analytics db
	 */
	public double getClaimsTurnaroundGoal();

	/**
	 * Sets the claims turnaround goal of this staging am analytics db.
	 *
	 * @param claimsTurnaroundGoal the claims turnaround goal of this staging am analytics db
	 */
	public void setClaimsTurnaroundGoal(double claimsTurnaroundGoal);

}