/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.service.base;

import com.argus.oth.account.management.model.AMAnalyticsDB;
import com.argus.oth.account.management.service.AMAnalyticsDBLocalService;
import com.argus.oth.account.management.service.AMAnalyticsDBLocalServiceUtil;
import com.argus.oth.account.management.service.persistence.AMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsDBPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsTelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMATelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsDBPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the am analytics db local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.argus.oth.account.management.service.impl.AMAnalyticsDBLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.argus.oth.account.management.service.impl.AMAnalyticsDBLocalServiceImpl
 * @generated
 */
public abstract class AMAnalyticsDBLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AMAnalyticsDBLocalService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AMAnalyticsDBLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AMAnalyticsDBLocalServiceUtil</code>.
	 */

	/**
	 * Adds the am analytics db to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsDBLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsDB the am analytics db
	 * @return the am analytics db that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsDB addAMAnalyticsDB(AMAnalyticsDB amAnalyticsDB) {
		amAnalyticsDB.setNew(true);

		return amAnalyticsDBPersistence.update(amAnalyticsDB);
	}

	/**
	 * Creates a new am analytics db with the primary key. Does not add the am analytics db to the database.
	 *
	 * @param amAnalyticsDbId the primary key for the new am analytics db
	 * @return the new am analytics db
	 */
	@Override
	@Transactional(enabled = false)
	public AMAnalyticsDB createAMAnalyticsDB(long amAnalyticsDbId) {
		return amAnalyticsDBPersistence.create(amAnalyticsDbId);
	}

	/**
	 * Deletes the am analytics db with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsDBLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsDbId the primary key of the am analytics db
	 * @return the am analytics db that was removed
	 * @throws PortalException if a am analytics db with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsDB deleteAMAnalyticsDB(long amAnalyticsDbId)
		throws PortalException {

		return amAnalyticsDBPersistence.remove(amAnalyticsDbId);
	}

	/**
	 * Deletes the am analytics db from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsDBLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsDB the am analytics db
	 * @return the am analytics db that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsDB deleteAMAnalyticsDB(AMAnalyticsDB amAnalyticsDB) {
		return amAnalyticsDBPersistence.remove(amAnalyticsDB);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AMAnalyticsDB.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return amAnalyticsDBPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsDBModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return amAnalyticsDBPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsDBModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return amAnalyticsDBPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return amAnalyticsDBPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return amAnalyticsDBPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AMAnalyticsDB fetchAMAnalyticsDB(long amAnalyticsDbId) {
		return amAnalyticsDBPersistence.fetchByPrimaryKey(amAnalyticsDbId);
	}

	/**
	 * Returns the am analytics db with the primary key.
	 *
	 * @param amAnalyticsDbId the primary key of the am analytics db
	 * @return the am analytics db
	 * @throws PortalException if a am analytics db with the primary key could not be found
	 */
	@Override
	public AMAnalyticsDB getAMAnalyticsDB(long amAnalyticsDbId)
		throws PortalException {

		return amAnalyticsDBPersistence.findByPrimaryKey(amAnalyticsDbId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(amAnalyticsDBLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsDB.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amAnalyticsDbId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			amAnalyticsDBLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AMAnalyticsDB.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"amAnalyticsDbId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(amAnalyticsDBLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsDB.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amAnalyticsDbId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return amAnalyticsDBLocalService.deleteAMAnalyticsDB(
			(AMAnalyticsDB)persistedModel);
	}

	public BasePersistence<AMAnalyticsDB> getBasePersistence() {
		return amAnalyticsDBPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return amAnalyticsDBPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the am analytics dbs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsDBModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of am analytics dbs
	 * @param end the upper bound of the range of am analytics dbs (not inclusive)
	 * @return the range of am analytics dbs
	 */
	@Override
	public List<AMAnalyticsDB> getAMAnalyticsDBs(int start, int end) {
		return amAnalyticsDBPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of am analytics dbs.
	 *
	 * @return the number of am analytics dbs
	 */
	@Override
	public int getAMAnalyticsDBsCount() {
		return amAnalyticsDBPersistence.countAll();
	}

	/**
	 * Updates the am analytics db in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsDBLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsDB the am analytics db
	 * @return the am analytics db that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsDB updateAMAnalyticsDB(AMAnalyticsDB amAnalyticsDB) {
		return amAnalyticsDBPersistence.update(amAnalyticsDB);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AMAnalyticsDBLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		amAnalyticsDBLocalService = (AMAnalyticsDBLocalService)aopProxy;

		_setLocalServiceUtilService(amAnalyticsDBLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AMAnalyticsDBLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AMAnalyticsDB.class;
	}

	protected String getModelClassName() {
		return AMAnalyticsDB.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = amAnalyticsDBPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AMAnalyticsDBLocalService amAnalyticsDBLocalService) {

		try {
			Field field = AMAnalyticsDBLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, amAnalyticsDBLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AMAnalyticsClaimPersistence amAnalyticsClaimPersistence;

	protected AMAnalyticsDBLocalService amAnalyticsDBLocalService;

	@Reference
	protected AMAnalyticsDBPersistence amAnalyticsDBPersistence;

	@Reference
	protected AMAnalyticsTelephonyPersistence amAnalyticsTelephonyPersistence;

	@Reference
	protected StagingAMAnalyticsClaimPersistence
		stagingAMAnalyticsClaimPersistence;

	@Reference
	protected StagingAMAnalyticsDBPersistence stagingAMAnalyticsDBPersistence;

	@Reference
	protected StagingAMATelephonyPersistence stagingAMATelephonyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}