/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.service.base;

import com.argus.oth.account.management.model.AMAnalyticsTelephony;
import com.argus.oth.account.management.service.AMAnalyticsTelephonyLocalService;
import com.argus.oth.account.management.service.AMAnalyticsTelephonyLocalServiceUtil;
import com.argus.oth.account.management.service.persistence.AMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsDBPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsTelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMATelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsDBPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the am analytics telephony local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.argus.oth.account.management.service.impl.AMAnalyticsTelephonyLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.argus.oth.account.management.service.impl.AMAnalyticsTelephonyLocalServiceImpl
 * @generated
 */
public abstract class AMAnalyticsTelephonyLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AMAnalyticsTelephonyLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AMAnalyticsTelephonyLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AMAnalyticsTelephonyLocalServiceUtil</code>.
	 */

	/**
	 * Adds the am analytics telephony to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsTelephonyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsTelephony the am analytics telephony
	 * @return the am analytics telephony that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsTelephony addAMAnalyticsTelephony(
		AMAnalyticsTelephony amAnalyticsTelephony) {

		amAnalyticsTelephony.setNew(true);

		return amAnalyticsTelephonyPersistence.update(amAnalyticsTelephony);
	}

	/**
	 * Creates a new am analytics telephony with the primary key. Does not add the am analytics telephony to the database.
	 *
	 * @param amAnalyticsTelephonyId the primary key for the new am analytics telephony
	 * @return the new am analytics telephony
	 */
	@Override
	@Transactional(enabled = false)
	public AMAnalyticsTelephony createAMAnalyticsTelephony(
		long amAnalyticsTelephonyId) {

		return amAnalyticsTelephonyPersistence.create(amAnalyticsTelephonyId);
	}

	/**
	 * Deletes the am analytics telephony with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsTelephonyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsTelephonyId the primary key of the am analytics telephony
	 * @return the am analytics telephony that was removed
	 * @throws PortalException if a am analytics telephony with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsTelephony deleteAMAnalyticsTelephony(
			long amAnalyticsTelephonyId)
		throws PortalException {

		return amAnalyticsTelephonyPersistence.remove(amAnalyticsTelephonyId);
	}

	/**
	 * Deletes the am analytics telephony from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsTelephonyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsTelephony the am analytics telephony
	 * @return the am analytics telephony that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsTelephony deleteAMAnalyticsTelephony(
		AMAnalyticsTelephony amAnalyticsTelephony) {

		return amAnalyticsTelephonyPersistence.remove(amAnalyticsTelephony);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AMAnalyticsTelephony.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return amAnalyticsTelephonyPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsTelephonyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return amAnalyticsTelephonyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsTelephonyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return amAnalyticsTelephonyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return amAnalyticsTelephonyPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return amAnalyticsTelephonyPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AMAnalyticsTelephony fetchAMAnalyticsTelephony(
		long amAnalyticsTelephonyId) {

		return amAnalyticsTelephonyPersistence.fetchByPrimaryKey(
			amAnalyticsTelephonyId);
	}

	/**
	 * Returns the am analytics telephony with the primary key.
	 *
	 * @param amAnalyticsTelephonyId the primary key of the am analytics telephony
	 * @return the am analytics telephony
	 * @throws PortalException if a am analytics telephony with the primary key could not be found
	 */
	@Override
	public AMAnalyticsTelephony getAMAnalyticsTelephony(
			long amAnalyticsTelephonyId)
		throws PortalException {

		return amAnalyticsTelephonyPersistence.findByPrimaryKey(
			amAnalyticsTelephonyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			amAnalyticsTelephonyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsTelephony.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"amAnalyticsTelephonyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			amAnalyticsTelephonyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AMAnalyticsTelephony.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"amAnalyticsTelephonyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			amAnalyticsTelephonyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsTelephony.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"amAnalyticsTelephonyId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return amAnalyticsTelephonyLocalService.deleteAMAnalyticsTelephony(
			(AMAnalyticsTelephony)persistedModel);
	}

	public BasePersistence<AMAnalyticsTelephony> getBasePersistence() {
		return amAnalyticsTelephonyPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return amAnalyticsTelephonyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the am analytics telephonies.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsTelephonyModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of am analytics telephonies
	 * @param end the upper bound of the range of am analytics telephonies (not inclusive)
	 * @return the range of am analytics telephonies
	 */
	@Override
	public List<AMAnalyticsTelephony> getAMAnalyticsTelephonies(
		int start, int end) {

		return amAnalyticsTelephonyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of am analytics telephonies.
	 *
	 * @return the number of am analytics telephonies
	 */
	@Override
	public int getAMAnalyticsTelephoniesCount() {
		return amAnalyticsTelephonyPersistence.countAll();
	}

	/**
	 * Updates the am analytics telephony in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsTelephonyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsTelephony the am analytics telephony
	 * @return the am analytics telephony that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsTelephony updateAMAnalyticsTelephony(
		AMAnalyticsTelephony amAnalyticsTelephony) {

		return amAnalyticsTelephonyPersistence.update(amAnalyticsTelephony);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AMAnalyticsTelephonyLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		amAnalyticsTelephonyLocalService =
			(AMAnalyticsTelephonyLocalService)aopProxy;

		_setLocalServiceUtilService(amAnalyticsTelephonyLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AMAnalyticsTelephonyLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AMAnalyticsTelephony.class;
	}

	protected String getModelClassName() {
		return AMAnalyticsTelephony.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				amAnalyticsTelephonyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AMAnalyticsTelephonyLocalService amAnalyticsTelephonyLocalService) {

		try {
			Field field =
				AMAnalyticsTelephonyLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, amAnalyticsTelephonyLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AMAnalyticsClaimPersistence amAnalyticsClaimPersistence;

	@Reference
	protected AMAnalyticsDBPersistence amAnalyticsDBPersistence;

	protected AMAnalyticsTelephonyLocalService amAnalyticsTelephonyLocalService;

	@Reference
	protected AMAnalyticsTelephonyPersistence amAnalyticsTelephonyPersistence;

	@Reference
	protected StagingAMAnalyticsClaimPersistence
		stagingAMAnalyticsClaimPersistence;

	@Reference
	protected StagingAMAnalyticsDBPersistence stagingAMAnalyticsDBPersistence;

	@Reference
	protected StagingAMATelephonyPersistence stagingAMATelephonyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}