/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.argus.oth.account.management.service.base;

import com.argus.oth.account.management.model.AMAnalyticsClaim;
import com.argus.oth.account.management.service.AMAnalyticsClaimLocalService;
import com.argus.oth.account.management.service.AMAnalyticsClaimLocalServiceUtil;
import com.argus.oth.account.management.service.persistence.AMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsDBPersistence;
import com.argus.oth.account.management.service.persistence.AMAnalyticsTelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMATelephonyPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsClaimPersistence;
import com.argus.oth.account.management.service.persistence.StagingAMAnalyticsDBPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the am analytics claim local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.argus.oth.account.management.service.impl.AMAnalyticsClaimLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.argus.oth.account.management.service.impl.AMAnalyticsClaimLocalServiceImpl
 * @generated
 */
public abstract class AMAnalyticsClaimLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AMAnalyticsClaimLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AMAnalyticsClaimLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AMAnalyticsClaimLocalServiceUtil</code>.
	 */

	/**
	 * Adds the am analytics claim to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsClaimLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsClaim the am analytics claim
	 * @return the am analytics claim that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsClaim addAMAnalyticsClaim(
		AMAnalyticsClaim amAnalyticsClaim) {

		amAnalyticsClaim.setNew(true);

		return amAnalyticsClaimPersistence.update(amAnalyticsClaim);
	}

	/**
	 * Creates a new am analytics claim with the primary key. Does not add the am analytics claim to the database.
	 *
	 * @param amAnalyticsClaimId the primary key for the new am analytics claim
	 * @return the new am analytics claim
	 */
	@Override
	@Transactional(enabled = false)
	public AMAnalyticsClaim createAMAnalyticsClaim(long amAnalyticsClaimId) {
		return amAnalyticsClaimPersistence.create(amAnalyticsClaimId);
	}

	/**
	 * Deletes the am analytics claim with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsClaimLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsClaimId the primary key of the am analytics claim
	 * @return the am analytics claim that was removed
	 * @throws PortalException if a am analytics claim with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsClaim deleteAMAnalyticsClaim(long amAnalyticsClaimId)
		throws PortalException {

		return amAnalyticsClaimPersistence.remove(amAnalyticsClaimId);
	}

	/**
	 * Deletes the am analytics claim from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsClaimLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsClaim the am analytics claim
	 * @return the am analytics claim that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMAnalyticsClaim deleteAMAnalyticsClaim(
		AMAnalyticsClaim amAnalyticsClaim) {

		return amAnalyticsClaimPersistence.remove(amAnalyticsClaim);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AMAnalyticsClaim.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return amAnalyticsClaimPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsClaimModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return amAnalyticsClaimPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsClaimModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return amAnalyticsClaimPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return amAnalyticsClaimPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return amAnalyticsClaimPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AMAnalyticsClaim fetchAMAnalyticsClaim(long amAnalyticsClaimId) {
		return amAnalyticsClaimPersistence.fetchByPrimaryKey(
			amAnalyticsClaimId);
	}

	/**
	 * Returns the am analytics claim with the primary key.
	 *
	 * @param amAnalyticsClaimId the primary key of the am analytics claim
	 * @return the am analytics claim
	 * @throws PortalException if a am analytics claim with the primary key could not be found
	 */
	@Override
	public AMAnalyticsClaim getAMAnalyticsClaim(long amAnalyticsClaimId)
		throws PortalException {

		return amAnalyticsClaimPersistence.findByPrimaryKey(amAnalyticsClaimId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			amAnalyticsClaimLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsClaim.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amAnalyticsClaimId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			amAnalyticsClaimLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AMAnalyticsClaim.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"amAnalyticsClaimId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			amAnalyticsClaimLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMAnalyticsClaim.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amAnalyticsClaimId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return amAnalyticsClaimLocalService.deleteAMAnalyticsClaim(
			(AMAnalyticsClaim)persistedModel);
	}

	public BasePersistence<AMAnalyticsClaim> getBasePersistence() {
		return amAnalyticsClaimPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return amAnalyticsClaimPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the am analytics claims.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.argus.oth.account.management.model.impl.AMAnalyticsClaimModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of am analytics claims
	 * @param end the upper bound of the range of am analytics claims (not inclusive)
	 * @return the range of am analytics claims
	 */
	@Override
	public List<AMAnalyticsClaim> getAMAnalyticsClaims(int start, int end) {
		return amAnalyticsClaimPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of am analytics claims.
	 *
	 * @return the number of am analytics claims
	 */
	@Override
	public int getAMAnalyticsClaimsCount() {
		return amAnalyticsClaimPersistence.countAll();
	}

	/**
	 * Updates the am analytics claim in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMAnalyticsClaimLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amAnalyticsClaim the am analytics claim
	 * @return the am analytics claim that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMAnalyticsClaim updateAMAnalyticsClaim(
		AMAnalyticsClaim amAnalyticsClaim) {

		return amAnalyticsClaimPersistence.update(amAnalyticsClaim);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AMAnalyticsClaimLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		amAnalyticsClaimLocalService = (AMAnalyticsClaimLocalService)aopProxy;

		_setLocalServiceUtilService(amAnalyticsClaimLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AMAnalyticsClaimLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AMAnalyticsClaim.class;
	}

	protected String getModelClassName() {
		return AMAnalyticsClaim.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = amAnalyticsClaimPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AMAnalyticsClaimLocalService amAnalyticsClaimLocalService) {

		try {
			Field field =
				AMAnalyticsClaimLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, amAnalyticsClaimLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AMAnalyticsClaimLocalService amAnalyticsClaimLocalService;

	@Reference
	protected AMAnalyticsClaimPersistence amAnalyticsClaimPersistence;

	@Reference
	protected AMAnalyticsDBPersistence amAnalyticsDBPersistence;

	@Reference
	protected AMAnalyticsTelephonyPersistence amAnalyticsTelephonyPersistence;

	@Reference
	protected StagingAMAnalyticsClaimPersistence
		stagingAMAnalyticsClaimPersistence;

	@Reference
	protected StagingAMAnalyticsDBPersistence stagingAMAnalyticsDBPersistence;

	@Reference
	protected StagingAMATelephonyPersistence stagingAMATelephonyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}