create table OTH_ClaimAnalytics (
	claimAnalyticsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	externalClientId LONG,
	clientName VARCHAR(75) null,
	claimNumber VARCHAR(75) null,
	externalCaseId LONG,
	claimStatus VARCHAR(75) null,
	receivedDate DATE null,
	serviceDate DATE null,
	paidDate DATE null,
	externalMemberId LONG,
	memberName VARCHAR(75) null,
	providerName VARCHAR(75) null,
	billType VARCHAR(75) null,
	primaryDiagnosis VARCHAR(75) null,
	chargedAmount DOUBLE,
	paidAmount DOUBLE,
	repricedAmount DOUBLE,
	savingsAmount DOUBLE,
	chargedPercent DOUBLE,
	repricedPercent DOUBLE,
	savingsPercent DOUBLE,
	chargedRange VARCHAR(75) null,
	paidRange VARCHAR(75) null,
	repricedRange VARCHAR(75) null,
	savingsRange VARCHAR(75) null,
	claimAging LONG,
	procedureCodes STRING null,
	resultCodes STRING null,
	diagnosisCodes STRING null,
	country VARCHAR(75) null,
	state_ VARCHAR(75) null,
	financialExposure DOUBLE,
	repricedNetwork VARCHAR(75) null,
	clientGroupName VARCHAR(75) null
);

create table OTH_StagingClaimAnalytics (
	stagingClaimAnalyticsId LONG not null primary key,
	createDate DATE null,
	modifiedDate DATE null,
	externalClientId LONG,
	clientName VARCHAR(75) null,
	claimNumber VARCHAR(75) null,
	externalCaseId LONG,
	claimStatus VARCHAR(75) null,
	receivedDate VARCHAR(75) null,
	serviceDate VARCHAR(75) null,
	paidDate VARCHAR(75) null,
	externalMemberId LONG,
	memberName VARCHAR(75) null,
	providerName VARCHAR(75) null,
	billType VARCHAR(75) null,
	primaryDiagnosis VARCHAR(75) null,
	chargedAmount DOUBLE,
	paidAmount DOUBLE,
	repricedAmount DOUBLE,
	savingsAmount DOUBLE,
	chargedPercent DOUBLE,
	repricedPercent DOUBLE,
	savingsPercent DOUBLE,
	chargedRange VARCHAR(75) null,
	paidRange VARCHAR(75) null,
	repricedRange VARCHAR(75) null,
	savingsRange VARCHAR(75) null,
	claimAging LONG,
	procedureCodes STRING null,
	resultCodes STRING null,
	diagnosisCodes STRING null,
	country VARCHAR(75) null,
	state_ VARCHAR(75) null,
	financialExposure DOUBLE,
	repricedNetwork VARCHAR(75) null,
	clientGroupName VARCHAR(75) null
);